(function(g){var window=this;'use strict';var P$R=function(B,z,T){g.D(function(R){B.T=g.yH(z,T);g.dX(R)})},YM=function(B){B.isActive()||B.start()},x1c=function(B,z){return z?B.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},vWF=function(B){return g.Zf(B)||B.D("web_enable_caption_language_preference_stickiness")},D1s=function(B,z){var T=new g.Lb;
T.languageCode=B.languageCode;T.languageName=B.languageName;T.name=B.name;T.displayName=B.displayName;T.kind=B.kind;T.isDefault=!1;T.T=B.T;T.isTranslateable=B.isTranslateable;T.vssId=B.vssId;T.url=B.url;T.translationLanguage=z;B.xtags&&(T.xtags=B.xtags);B.captionId&&(T.captionId=B.captionId);return T},k0q=function(B,z){var T,R,h;
return g.D(function(W){if(W.U==1)return T=B+"|"+z,g.P(W,g.Sd(),2);if(W.U!=3){R=W.T;if(!R)throw g.Uj("gct");return g.P(W,g.P3(R),3)}h=W.T;return W.return(h.get("captions",T))})},Kbp=function(B,z,T){k0q(B,z).then(function(R){R&&T(R.trackData,new g.Lb(R.metadata))})},uLP=function(B){if(!m1c.test(B))throw Error("'"+B+"' is not a valid hex color");
B.length==4&&(B=B.replace(nWP,"#$1$1$2$2$3$3"));B=B.toLowerCase();B=parseInt(B.slice(1),16);return[B>>16,B>>8&255,B&255]},Hec=function(){var B=void 0;
B=B===void 0?{}:B;var z="suggest_correction"in g.irc?g.irc.suggest_correction:"Edit caption";z=z||"";var T={},R;for(R in B){T={x6:T.x6};T.x6=R;var h=function(W){return function(){return String(B[W.x6])}}(T);
z=z.replace(new RegExp("\\$\\{"+T.x6+"\\}","gi"),h);z=z.replace(new RegExp("\\$"+T.x6,"gi"),h)}return z},f0h=function(){return g.kK("yt-player-caption-display-settings")},lk=function(){this.segments=[]},Oeg=function(B,z){var T=g.$P(B.segments,z);
T>=0||T<0&&(-T-1)%2===1||(T=-T-1,T>0&&z-B.segments[T-1]===1&&T<B.segments.length&&B.segments[T]-z===1?(g.IR(B.segments,T),g.IR(B.segments,T-1)):T>0&&z-B.segments[T-1]===1?B.segments[T-1]=z:T<B.segments.length&&B.segments[T]-z===1?B.segments[T]=z:(g.yq(B.segments,T,0,z),g.yq(B.segments,T+1,0,z)))},NqR=function(B,z,T,R,h,W){g.K.call(this);
this.policy=B;this.player=z;this.TZ=T;this.J=R;this.V=h;this.N=W;this.W=new lk;this.X=-1;this.Y=this.U=this.T=null;this.UE=0;this.L=new g.Si(this.YU,1E3,this);this.events=new g.kb(this);g.m(this,this.L);g.m(this,this.events);this.events.Z(z,"SEEK_COMPLETE",this.k_);this.k_();this.YU()},tKh=function(B){return B.T&&B.T.X?B.T.X+B.player.p4()<B.player.getCurrentTime():!1},jFh=function(B,z){if(B.policy.nt&&B.player.Og()){var T=g.jI(z,B.policy,{});
T.set("pot",B.player.Og());T=T.Pu()}else T=g.jI(z,B.policy,{}).Pu();var R={format:"RAW",withCredentials:!0};if(B.policy.zZ){R.method="POST";var h=z.W;h&&Object.keys(h).length>0?R.postBody=g.wz(h,g.Rf):R.postBody=(0,g.d7)([120,0])}B.V&&(R.responseType="arraybuffer");var W=++B.UE,b=(0,g.f)();B.Y=g.$v(T,R,3,100).then(function(l){if(B.policy.ix&&W%100===1){var w=(0,g.f)();B.player.OE("caprsp",{rn:W,ms:w-b,kb:(l.xhr.responseText.length/1024).toFixed()})}a:{l=l.xhr;B.xd();if(B.U){var q=!(B.V?l.response:
l.responseText)||l.status>=400;if(w=g.TeP(l)){l=g.jI(B.U,B.policy,{});B.U.yG(l,w);jFh(B,B.U);break a}if(q)B.player.OE("capfail",{status:l.status});else{var c;g.JO("fcb_r",(0,g.f)(),((c=B.player.getVideoData())==null?void 0:c.N)||"");c=B.U.oK[0].FE;B.J!=null&&B.X!==c&&(w=B.U.oK[0],B.V?B.J(l.response,(w.startTime+B.player.p4())*1E3):B.J(l.responseText,(w.startTime+B.player.p4())*1E3),B.X=c)}}B.U=null;B.Y=null}}).d2(function(l){B.U=null;
B.Y=null;var w;B.player.OE("capfail",{rn:W,status:(w=l.xhr)==null?void 0:w.status})});
B.U=z;Oeg(B.W,B.U.oK[0].FE)},wT=function(B,z){g.dh.call(this,z);
this.T=B;this.j=z;this.Y=null;this.X=!1;this.logger=new g.RH("caps");this.L=g.mfB(this.j,this.T)},Zep=function(B,z){var T=[],R;
for(R in B.T.T)if(B.T.T.hasOwnProperty(R)){var h=B.T.T[R];if(g.a$(h,z||null)){var W=h.info.id,b=W,l="."+W,w="",q="";if(h=h.info.captionTrack)W=h.languageCode,b=h.displayName,l=h.vssId,w=h.kind,q=h.id;else{h=W;var c=g.xlh.get(h);c==null&&(c=XDg[h]||XDg[h.replace(/-/g,"_")],g.xlh.set(h,c));h=c;b=h||b}T.push(new g.Lb({id:R,languageCode:W,languageName:b,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:w,captionId:q}))}}return T},e5R=function(B,z){return z!=null&&z in B.T.T?B.T.T[z]:null},
sFh=function(B,z,T){var R=[],h;
for(h in B.T.T)if(B.T.T.hasOwnProperty(h)){var W=B.T.T[h];if(g.a$(W,T||null)){var b=W.info.captionTrack;b&&b.languageCode===z&&R.push(W)}}return R.length?R[0]:null},qd=function(B,z,T,R,h,W,b,l,w,q){var c=q.isInline()&&!0,L={};
Object.assign(L,z);Object.assign(L,B.params);Object.assign(L,T);var C={};Object.assign(C,z.Tj);B.params.Tj&&Object.assign(C,B.params.Tj);Object.assign(C,T.Tj);c&&(L.windowOpacity=.6,C.backgroundOpacity=0);L.Tj=C;var r=L.Sw===1,F=[{B:"span",G:"captions-text",C:{style:"word-wrap: normal; display: block;"}}],A,a,V;(l=l.Cf("caption_edit_on_hover")&&((A=q.getVideoData().getPlayerResponse())==null?void 0:(a=A.captions)==null?void 0:(V=a.playerCaptionsTracklistRenderer)==null?void 0:V.openTranscriptCommand))&&
F.unshift({B:"button",G:"caption-edit",C:{tabindex:"0","aria-label":Hec()},S:[{B:"svg",C:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},S:[{B:"path",C:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.O.call(this,{B:"div",G:"caption-window",C:{id:"caption-window-"+B.id,dir:r?"rtl":"ltr",tabindex:"0",lang:L.lang},S:F});var M=
this;this.L=[];this.XE=!1;this.U=B;this.lO=this.zZ=null;this.II=W;this.C4=b;this.J=null;this.maxWidth=W*.96;this.maxHeight=b*.96;this.T=L;this.s0=T;this.UE=z;this.W=this.BD("captions-text");this.Dm=this.W.style.getPropertyValue("box-decoration-break")!==""||this.W.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.IK=EW7(R,h,W,b);this.JZ=w;l&&(this.X=this.BD("caption-edit"),this.Z(this.X,"click",function(){M.JZ()}));
this.type=0;this.Kf=this.IK*SMK(C);this.aK=c;B=new g.nn(this.element,!0);g.m(this,B);B.subscribe("dragstart",this.bE,this);B.subscribe("dragmove",this.W9,this);B.subscribe("dragend",this.QR,this);this.MG=this.sE=this.EE=this.eI=0;B="";this.T.windowOpacity&&(B=uLP(this.T.windowColor),B="rgba("+B[0]+","+B[1]+","+B[2]+","+this.T.windowOpacity+")");z={"background-color":B,display:this.T.isVisible===!1?"none":"","text-align":BgF[this.T.textAlign]};this.Dm&&(z["border-radius"]=B?this.Kf/8+"px":"");(this.Y=
this.U.params.Sw===2||this.U.params.Sw===3)&&z3s(this,this.element);g.Ml(this.element,z);if(c){var x;(x=this.element.parentElement)==null||x.style.setProperty("--caption-window-color",B)}switch(this.T.qL){case 0:case 1:case 2:g.ww(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.ww(this.element,"ytp-caption-window-bottom")}},z3s=function(B,z){var T="vertical-rl";
B.T.AX===1&&(T="vertical-lr");g.Ff&&(T=T==="vertical-lr"?"tb-lr":"tb-rl");g.Ml(z,"-o-writing-mode",T);g.Ml(z,"-webkit-writing-mode",T);g.Ml(z,"writing-mode",T);g.Ml(z,"text-orientation","upright");g.ww(z,"ytp-vertical-caption");B.U.params.Sw===3&&(g.Ml(z,"text-orientation",""),g.Ml(z,"transform","rotate(180deg)"))},SMK=function(B){var z=1+.25*(B.fontSizeIncrement||0);
if(B.offset===0||B.offset===2)z*=.8;return z},TgI=function(B,z){var T={},R=z.background?z.background:B.T.Tj.background;
if(z.backgroundOpacity!=null||z.background){var h=z.backgroundOpacity!=null?z.backgroundOpacity:B.T.Tj.backgroundOpacity;R=uLP(R);T.background="rgba("+R[0]+","+R[1]+","+R[2]+","+h+")";B.Dm&&(T["box-decoration-break"]="clone",T["border-radius"]=B.Kf/8+"px")}if(z.fontSizeIncrement!=null||z.offset!=null)T["font-size"]=B.IK*SMK(z)+"px";R=1;h=z.color||B.T.Tj.color;if(z.color||z.textOpacity!=null)h=uLP(h),R=z.textOpacity==null?B.T.Tj.textOpacity:z.textOpacity,h="rgba("+h[0]+","+h[1]+","+h[2]+","+R+")",
T.color=h,T.fill=h;var W=z.charEdgeStyle;W===0&&(W=void 0);if(W){h="rgba(34, 34, 34, "+R+")";var b="rgba(204, 204, 204, "+R+")";z.Cz&&(b=h=z.Cz);var l=B.IK/16/2,w=Math.max(l,1),q=Math.max(2*l,1),c=Math.max(3*l,1),L=Math.max(5*l,1);R=[];switch(W){case 4:for(;c<=L;c+=l)R.push(q+"px "+q+"px "+c+"px "+h);break;case 1:q=window.devicePixelRatio>=2?.5:1;for(W=w;W<=c;W+=q)R.push(W+"px "+W+"px "+h);break;case 2:R.push(w+"px "+w+"px "+b);R.push("-"+w+"px -"+w+"px "+h);break;case 3:for(c=0;c<5;c++)R.push("0 0 "+
q+"px "+h)}T["text-shadow"]=R.join(", ")}h="";switch(z.fontFamily){case 1:h='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:h='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:h='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:h='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:h='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:h=g.jH()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:h='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}h&&(T["font-family"]=h);h=z.offset;h==null&&(h=B.T.Tj.offset);switch(h){case 0:T["vertical-align"]="sub";break;case 2:T["vertical-align"]="super"}z.fontFamily===7&&(T["font-variant"]="small-caps");z.bold&&(T["font-weight"]="bold");z.italic&&(T["font-style"]="italic");z.underline&&(T["text-decoration"]=
"underline");z.ym&&(T.visibility="hidden");z.X$===1&&B.Y&&(T["text-combine-upright"]="all",T["text-orientation"]="mixed",h=g.Ef||g.Ax,B.U.params.Sw===3?T.transform=h?"rotate(90deg)":"rotate(180deg)":h&&(T.transform="rotate(-90deg)"));if(z.textEmphasis===1||z.textEmphasis===2||z.textEmphasis===3||z.textEmphasis===4||z.textEmphasis===5)if(g.Ef)T["font-weight"]="bold";else switch(T["text-emphasis-style"]="filled circle",T["text-emphasis-color"]="currentcolor",T["webkit-text-emphasis"]="filled circle",
z.textEmphasis){case 4:case 3:T["text-emphasis-position"]="under left";T["webkit-text-emphasis-position"]="under left";break;case 5:case 2:T["text-emphasis-position"]="over right",T["webkit-text-emphasis-position"]="over right"}return T},ik=function(B){B=B.split("px");
return B.length>0?(B=Number(B[0]))?B:0:0},R3U=function(B){B.J=g.ES("SPAN");
g.Ml(B.J,{display:"block"});g.ww(B.J,"caption-visual-line");B.W.appendChild(B.J)},h3q=function(B,z){var T=g.ES("SPAN");
g.Ml(T,{display:"inline-block","white-space":"pre-wrap"});g.Ml(T,TgI(B,z));T.classList.add("ytp-caption-segment");B.J.appendChild(T);T.previousElementSibling&&(g.Ml(T.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.Ml(T,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return T},W97=function(B,z,T){B.XE=B.XE||!!T;
var R={};Object.assign(R,B.T.Tj);Object.assign(R,T||z.T);Object.assign(R,B.s0.Tj);(T=!B.J)&&R3U(B);for(var h=B.zZ&&B.lO&&g.Bh(R,B.lO)?B.zZ:h3q(B,R),W=typeof z.text==="string",b=W?z.text.split("\n"):[z.text],l=0;l<b.length;l++){var w=l>0||!z.append,q=b[l];w&&!T?(R3U(B),h=h3q(B,R)):w&&T&&(T=!1);q&&(h.appendChild(W?g.Sh(q):q),W||q.tagName!=="RUBY"||q.childElementCount!==4||g.Ef||!g.QC(q.children[2],"text-emphasis")||(w=B.Y?"padding-right":"padding-top",g.QC(q.children[2],"text-emphasis-position")&&(w=
B.Y?"padding-left":"padding-bottom"),g.X8?g.Ml(h,w,"1em"):g.Ml(h,w,"0.5em")))}B.lO=R;B.zZ=h;B.L.push(z)},EW7=function(B,z,T,R){var h=z/360*16;
z>=B&&(B=640,R>T*1.3&&(B=480),h=T/B*16);return h},YOW=function(){this.Y=this.time=this.mode=this.U=0;
this.W=new bgg(this);this.V=new bgg(this);this.T=[];this.clear()},wWq=function(B,z,T){if(B===255&&z===255||!B&&!z)return{gT:B,
n6:z,result:0};B=lpP[B];z=lpP[z];if(B&128){var R;if(R=!(z&128))R=z,R=T.u1()&&T.n6===R;if(R)return{gT:B,n6:z,result:1}}else if(z&128&&1<=B&&B<=31)return{gT:B,n6:z,result:2};return{gT:B,n6:z,result:3}},igs=function(B,z,T,R){z===255&&T===255||!z&&!T?(++B.Y===45&&B.reset(),B.W.U.clear(),B.V.U.clear()):(B.Y=0,qOg(B.W,z,T,R))},c4c=function(B,z){B.T.sort(function(h,W){var b=h.time-W.time;
return b===0?h.order-W.order:b});
for(var T=g.d(B.T),R=T.next();!R.done;R=T.next())R=R.value,B.time=R.time,R.type===0?igs(B,R.Vp,R.D2,z):R.type===1&&B.U&496&&qOg(B.V,R.Vp,R.D2,z);B.T.length=0},cC=function(){this.type=0},Lw=function(){this.state=this.n6=this.gT=0},L9W=function(){this.timestamp=this.T=0},Cw=function(B){this.V=B;
this.Y=[];this.T=this.U=this.row=0;this.style=new cC;for(B=this.W=0;B<=15;B++){this.Y[B]=[];for(var z=0;z<=32;z++)this.Y[B][z]=new L9W}},rT=function(B,z){if(B.style.type===3){for(var T=0,R=0,h=B.V.time+0,W="",b="",l=h,w=1;w<=15;++w){for(var q=!1,c=R?R:1;c<=32;++c){var L=B.Y[w][c];
if(L.T!==0){T===0&&(T=w,R=c);q=String.fromCharCode(L.T);var C=L.timestamp;C<h&&(h=C);L.timestamp=l;b&&(W+=b,b="");W+=q;q=!0}if((L.T===0||c===32)&&q){b="\n";break}else if(R&&!q)break}if(T&&!q)break}W&&z.W(T,R,h,l,W)}else for(R=T=0,W=h=B.V.time+0,b=1;b<=15;++b)for(l="",w=1;w<=32;++w)if(c=B.Y[b][w],L=c.T,L!==0&&(T===0&&(T=b,R=w),q=String.fromCharCode(L),C=c.timestamp,C<=h&&(h=C),l+=q,c.reset()),w===32||L===0)l&&z.W(T,R,h,W,l),h=W,l="",R=T=0},IpR=function(B,z){switch(B){case 0:return CMW[(z&127)-32];
case 1:return r4P[z&15];case 2:return owq[z&31];case 3:return F9c[z&31]}return 0},ok=function(B){return B.Y[B.row][B.U]},Fq=function(B,z,T){z>=2&&B.U>1&&(--B.U,ok(B).T=0);
var R=ok(B);R.timestamp=B.V.time+0;R.T=IpR(z,T);B.U<32&&B.U++},GBU=function(B,z,T,R){for(var h=0;h<R;h++)for(var W=0;W<=32;W++){var b=B.Y[z+h][W],l=B.Y[T+h][W];
b.T=l.T;b.timestamp=l.timestamp}},Ik=function(B,z,T){for(var R=0;R<T;R++)for(var h=0;h<=32;h++)B.Y[z+R][h].reset()},das=function(B){B.row=B.T>0?B.T:1;
B.U=1;Ik(B,0,15)},A4W=function(B){this.Y=B;
this.V=0;this.style=new cC;this.X=new Cw(this.Y);this.L=new Cw(this.Y);this.text=new Cw(this.Y);this.U=this.X;this.W=this.L;this.T=this.U},apW=function(B,z,T){var R=B.U,h=!1;
switch(B.style.get()){case 4:case 1:case 2:B.style.get()===4&&R.T>0||(rT(R,T),das(B.U),das(B.W),R.row=15,R.T=z,h=!0)}B.style.set(3);B.T=R;B.T.style=B.style;B.Y.mode=1<<R.W;h?R.U=1:R.T!==z&&(R.T>z?(rT(R,T),Ik(R,R.row-R.T,z)):R.row<z&&(z=R.T),R.T=z)},Ua5=function(B){B.style.set(1);
B.T=B.W;B.T.T=0;B.T.style=B.style;B.Y.mode=1<<B.T.W},MUg=function(B){B.style.set(4);
B.T=B.text;B.T.style=B.style;B.Y.mode=1<<B.T.W},bgg=function(B){this.T=B;
this.V=0;this.Y=new A4W(this.T);this.X=new A4W(this.T);this.U=new Lw;this.W=this.Y},qOg=function(B,z,T,R){B.U.update();
z=wWq(z,T,B.U);switch(z.result){case 0:return;case 1:case 2:return}var h=z.gT;T=z.n6;if(32<=h||!h)B.T.mode&B.T.U&&(z=h,z&128&&(z=127),T&128&&(T=127),B=B.W.T,z&96&&Fq(B,0,z),T&96&&Fq(B,0,T),z!==0&&T!==0&&B.style.type===3&&rT(B,R));else if(h&16)a:if(!B.U.matches(h,T)&&(z=B.U,z.gT=h,z.n6=T,z.state=2,z=h&8?B.X:B.Y,B.W=z,B.T.mode=1<<(B.V<<2)+(z.V<<1)+(z.style.type===4?1:0),(B.T.mode|1<<(B.V<<2)+(z.V<<1)+(z.style.type!==4?1:0))&B.T.U))if(T&64){R=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(h&7)<<1|T>>5&1];
B=T&16?((T&14)>>1)*4:0;T=z.T;switch(z.style.get()){case 4:R=T.row;break;case 3:if(R!==T.row){if(R<T.T&&(R=T.T,R===T.row))break;var W=1+T.row-T.T,b=1+R-T.T;GBU(T,b,W,T.T);z=W;h=T.T;b<W?(W=b+h-W,W>0&&(z+=W,h-=W)):(W=W+h-b,W>0&&(h-=W));Ik(T,z,h)}}T.row=R;T.U=B+1}else switch(h&7){case 1:switch(T&112){case 32:Fq(z.T,0,32);break a;case 48:T===57?(R=z.T,ok(R).T=0,R.U<32&&R.U++):Fq(z.T,1,T&15)}break;case 2:T&32&&Fq(z.T,2,T&31);break;case 3:T&32&&Fq(z.T,3,T&31);break;case 4:case 5:if(32<=T&&T<=47)switch(T){case 32:Ua5(z);
break;case 33:R=z.T;R.U>1&&(--R.U,ok(R).T=0);break;case 36:R=z.T;z=ok(R);for(B=0;B<=15;B++)for(T=0;T<=32;T++)if(R.Y[B][T]===z){for(;T<=32;T++)R.Y[B][T].reset();break}break;case 37:apW(z,2,R);break;case 38:apW(z,3,R);break;case 39:apW(z,4,R);break;case 40:Fq(z.T,0,32);break;case 41:z.style.set(2);z.T=z.U;z.T.T=0;z.T.style=z.style;z.Y.mode=1<<z.T.W;break;case 42:R=z.text;R.T=15;R.style.set(4);das(R);MUg(z);break;case 43:MUg(z);break;case 44:B=z.U;switch(z.style.get()){case 1:case 2:case 3:rT(B,R)}Ik(B,
0,15);break;case 45:b:{B=z.T;switch(z.style.get()){default:case 2:case 1:break b;case 4:if(B.row<15){++B.row;B.U=1;break b}break;case 3:}B.T<2&&(B.T=2,B.row<B.T&&(B.row=B.T));z=B.row-B.T+1;rT(B,R);GBU(B,z,z+1,B.T-1);Ik(B,B.row,1)}break;case 46:Ik(z.W,0,15);break;case 47:rT(z.U,R),z.W.updateTime(z.Y.time+0),R=z.W,z.W=z.U,z.U=R,Ua5(z)}break;case 7:switch(T){case 33:case 34:case 35:R=z.T,(R.U+=T&3)>32&&(R.U=32)}}},VUK=function(){},GA=function(B,z,T,R,h,W,b){W=W===void 0?!1:W;
b=b===void 0?null:b;g.Wj.call(this,B,B+z,{priority:T,namespace:"captions"});this.windowId=R;this.text=h;this.append=W;this.T=b},y4P=function(B,z,T,R,h,W,b){var l=W[0],w=b[l.getAttribute("p")];
if(w.DR===1){var q=W[1],c=W[2];W=W[3];l.getAttribute("t");q.getAttribute("t");c.getAttribute("t");W.getAttribute("t");l.getAttribute("p");q.getAttribute("p");W.getAttribute("p");b=b[c.getAttribute("p")];l=QaW(l.textContent,q.textContent,c.textContent,W.textContent,b);return new GA(B,z,h,T,l,R,w)}switch(w.DR){case 9:case 10:w.textEmphasis=1;break;case 11:w.textEmphasis=2;break;case 12:w.textEmphasis=3;break;case 13:w.textEmphasis=4;break;case 14:w.textEmphasis=5}return new GA(B,z,h,T,l.textContent||
"",R,w)},QaW=function(B,z,T,R,h){var W=g.jH(),b=W?g.ES("DIV"):g.ES("RUBY"),l=g.ES("SPAN");
l.textContent=B;b.appendChild(l);B=W?g.ES("DIV"):g.ES("RP");B.textContent=z;b.appendChild(B);z=W?g.ES("DIV"):g.ES("RT");z.textContent=T;b.appendChild(z);T=h.DR;if(T===10||T===11||T===12||T===13||T===14)if(g.Ml(z,"text-emphasis-style","filled circle"),g.Ml(z,"text-emphasis-color","currentcolor"),g.Ml(z,"webkit-text-emphasis","filled circle"),h.DR===11||h.DR===13)g.Ml(z,"webkit-text-emphasis-position","under left"),g.Ml(z,"text-emphasis-position","under left");T=!0;if(h.DR===4||h.DR===7||h.DR===12||
h.DR===14)g.Ml(b,"ruby-position","over"),g.Ml(b,"-webkit-ruby-position","before");else if(h.DR===5||h.DR===6||h.DR===11||h.DR===13)g.Ml(b,"ruby-position","under"),g.Ml(b,"-webkit-ruby-position","after"),T=!1;h=W?g.ES("DIV"):g.ES("RP");h.textContent=R;b.appendChild(h);W&&(R=T,g.Ml(b,{display:"inline-block",position:"relative"}),W=b.firstElementChild.nextElementSibling,g.Ml(W,"display","none"),W=W.nextElementSibling,g.Ml(W,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.Ml(b.lastElementChild,"display","none"),R?(g.Ml(b,"padding-top","0.6em"),g.Ml(W,"top","0")):(g.Ml(b,"padding-bottom","0.6em"),g.Ml(W,"bottom","0")));return b},dT=function(){g.K.apply(this,arguments)},At=function(B,z,T,R,h){g.Wj.call(this,B,B+z,{priority:T,
namespace:"captions"});this.id=R;this.params=h;this.T=[]},gwc=function(B){var z="_"+ak++;
return new At(0,0x8000000000000,0,z,B)},UX=function(B){dT.call(this);
this.Y=B;this.pens={};this.L={};this.J={};this.W="_"+ak++;this.X={};this.U=this.T=null;this.V=!0},Md=function(B,z){B=B.getAttribute(z);
if(B!=null)return Number(B)},Vs=function(B,z){B=B.getAttribute(z);
if(B!=null)return B==="1"},Qs=function(B,z){B=Md(B,z);
return B!==void 0?B:null},gT=function(B,z){B=B.getAttribute(z);
if(B!=null)return ys.test(B),B},J4F=function(B,z){var T={},R=z.getAttribute("ws");
Object.assign(T,R?B.J[R]:B.Y);B=Qs(z,"mh");B!=null&&(T.AI=B);B=Qs(z,"ju");B!=null&&(T.textAlign=B);B=Qs(z,"pd");B!=null&&(T.Sw=B);B=Qs(z,"sd");B!=null&&(T.AX=B);B=gT(z,"wfc");B!=null&&(T.windowColor=B);z=Md(z,"wfo");z!==void 0&&(T.windowOpacity=z/255);return T},pWh=function(B,z){var T={},R=z.getAttribute("wp");
R&&Object.assign(T,B.L[R]);B=Qs(z,"ap");B!=null&&(T.qL=B);B=Md(z,"cc");B!=null&&(T.zI=B);B=Md(z,"ah");B!=null&&(T.mX=B);B=Md(z,"rc");B!=null&&(T.Jb=B);z=Md(z,"av");z!=null&&(T.pU=z);return T},$aF=function(B,z,T,R){var h={};
Object.assign(h,pWh(B,z));Object.assign(h,J4F(B,z));R?g.Bh(h,B.Y)?(R=B.W,h=B.Y):R="_"+ak++:R=z.getAttribute("id")||"_"+ak++;B=Md(z,"t")+T;z=Md(z,"d")||0x8000000000000;if(h.Sw===2||h.Sw===3)T=h.Jb,h.Jb=h.zI,h.zI=T;return new At(B,z,0,R,h)},Jt=function(B){dT.call(this);
this.V=B;this.T=new Map;this.Y=new Map;this.W=new Map;this.U=new Map},pw=function(B){B=g.yQ(Math.round(B),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-B.length)+B},PMq=function(B,z,T,R,h){R===0&&(R=0x8000000000000);
var W={};z.wpWinPosId&&Object.assign(W,B.Y.get(z.wpWinPosId));z.wsWinStyleId&&Object.assign(W,B.W.get(z.wsWinStyleId));B=z.rcRowCount;B!==void 0&&(W.Jb=B);z=z.ccColCount;z!==void 0&&(W.zI=z);if(W.Sw===2||W.Sw===3)z=W.Jb,W.Jb=W.zI,W.zI=z;return new At(T,R,0,h,W)},$M=function(B,z,T){g.dh.call(this,B);
this.videoData=z;this.audioTrack=T;this.V=z.qs},PC=function(B,z,T,R,h,W,b,l,w,q){qd.call(this,B,z,T,R,h,W,b,l,w,q);
this.type=1},xM=function(B,z,T){this.trackData=B;
this.X=T;this.version=this.V=this.Y=this.byteOffset=0;this.U=[];this.T=new DataView(this.trackData)},vC=function(B){var z=B.byteOffset;
B.byteOffset+=1;return B.T.getUint8(z)},DP=function(B){var z=B.byteOffset;
B.byteOffset+=4;return B.T.getUint32(z)},kM=function(B,z){dT.call(this);
this.U=B;this.Y=z;this.track=this.Y.languageName==="CC3"?4:0;this.T=new YOW;this.T.U=1<<this.track},vwh=function(B){if(typeof B==="string")return!1;
B=new xM(B,8,0);return xaI(B)},xaI=function(B){if(!(B.byteOffset<B.T.byteLength)||DP(B)!==1380139777)return!1;
B.version=vC(B);if(B.version>1)return!1;vC(B);vC(B);vC(B);return!0},Kw=function(B,z,T,R,h,W,b,l,w,q){qd.call(this,B,z,T,R,h,W,b,l,w,q);
var c=this;this.type=2;this.WD=[];this.TZ=this.N=this.cD=0;this.RK=NaN;this.U0=0;this.ra=null;this.O0=new g.Si(this.KO,433,this);this.X&&(q.createClientVe(this.X,this,167342),this.Z(this.X,"click",function(){q.logClick(c.X)}),B=new g.nn(this.element,!0),g.m(this,B),B.subscribe("hoverstart",function(){q.logVisibility(c.X,!0)},this));
g.ww(this.element,"ytp-caption-window-rollup");g.m(this,this.O0);g.Ml(this.element,"overflow","hidden")},DaF=function(B,z){if(!z)return"";
B.Y&&B.U.params.AX!==1&&(z*=-1);return"translate"+(B.Y?"X":"Y")+"("+z+"px)"},kB5=function(B){B.WD=Array.from(B.element.getElementsByClassName("caption-visual-line"));
for(var z=B.U.params.Jb,T=0,R=0,h=B.WD.length-1;T<z&&h>-1;){var W=B.WD[h];R+=B.Y?W.offsetWidth:W.offsetHeight;T++;h--}B.N=R;z=Math;T=z.max;isNaN(B.RK)&&((R=B.T.zI)?(h=g.ES("SPAN"),g.Wt(h,"\u2013".repeat(R)),g.Ml(h,TgI(B,B.T.Tj)),B.W.appendChild(h),B.RK=h.offsetWidth,B.W.removeChild(h)):B.RK=0);R=B.W;B.TZ=T.call(z,B.RK,B.U0,(B.Y?R.offsetHeight:R.offsetWidth)+1)},K9F=function(B,z){kB5(B);
var T=B.WD.reduce(function(W,b){return(B.Y?b.offsetWidth:b.offsetHeight)+W},0);
T=B.N-T;if(T!==B.cD){var R=T>0&&B.cD===0,h=T<B.cD;z||isNaN(T)||R||!h||(g.ww(B.element,"ytp-rollup-mode"),B.Z(B.element,"transitionend",B.KO));g.Ml(B.W,"transform",DaF(B,T));B.cD=T}kB5(B)},mac=function(B,z,T,R){var h=this;
this.j=B;this.Y=z;this.logger=T;this.PB=R;this.Tz=[];this.Ev=[];this.T=null;this.Yi={njJ:function(){return h.T},
Ao:function(){return h.Tz}};
B=g.rk(this.j.K().experiments,"html5_override_micro_discontinuities_threshold_ms");this.U=B>0?B:10},Hg7=function(B,z){B.T=function(T,R){if(T.info.V){var h=T;
if(B.Ev.length>0){for(h=B.Ev.shift();B.Ev.length>0;)h=g.bP(h,B.Ev.shift());h=g.bP(h,T)}if(h){T=h;try{var W=g.Yf(T)*1E3}catch(q){W=T.info.startTime*1E3}try{var b=g.txz(T)*1E3}catch(q){b=T.info.duration*1E3}if(W<0||b<0)W<0&&(W=T.info.startTime*1E3),b<0&&(b=T.info.duration*1E3);T.info.startTime=W/1E3;T.info.W=W/1E3;T.info.duration=b/1E3;T.info.L=b/1E3;W=B.uj(h);b=W.FE;W={formatId:W.formatId,startTimeMs:W.startTimeMs,durationMs:W.durationMs,w0:b,bf:b};b=nwF(B.Tz,W.startTimeMs);var l=(T=b>=0?B.Tz[b]:null)?
T.startTimeMs+T.durationMs:0,w=W.startTimeMs+W.durationMs;!T||W.startTimeMs-l>B.U?B.Tz.splice(b+1,0,W):(T.durationMs=Math.max(l,w)-T.startTimeMs,T.bf=Math.max(T.bf,W.bf));R(B.Tz);R=h.YL();upP(B.Y,R.buffer.slice(R.byteOffset,R.byteLength+R.byteOffset),z,h.info.W)}else B.logger.T(350058965,"Empty slice")}else B.Ev.push(T)};
B.j.addEventListener("sabrCaptionsDataLoaded",B.T)},nwF=function(B,z){B=g.$P(B,{startTimeMs:z},function(T,R){return T.startTimeMs-R.startTimeMs});
return B>=0?B:-B-2},fpI=function(B,z){g.dh.call(this,z);
this.T=B;this.j=z;this.logger=new g.RH("caps");this.Y=this.X=null;this.L=new mac(this.j,this,this.logger,this.T.PB)},upP=function(B,z,T,R){B.logger.debug(function(){return"SABR captions data received for "+R});
B.X?B.Y==null?B.logger.T(350058965,"Null loaded track meta data at captions data received"):T.Mm(z,B.Y,R*1E3):B.logger.T(350058965,"Null Representation at captions data received")},OgP=function(B,z){var T=[],R;
for(R in B.T.T)if(B.T.T.hasOwnProperty(R)){var h=B.T.T[R];if(g.a$(h,z||null)){var W=h.info.id,b=W,l="."+W,w="",q="";if(h=h.info.captionTrack)W=h.languageCode,b=h.displayName,l=h.vssId,w=h.kind,q=h.id;T.push(new g.Lb({id:R,languageCode:W,languageName:b,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:w,captionId:q}))}}return T},Ngp=function(B,z,T){var R=[],h;
for(h in B.T.T)if(B.T.T.hasOwnProperty(h)){var W=B.T.T[h];if(g.a$(W,T||null)){var b=W.info.captionTrack;b&&b.languageCode===z&&R.push(W)}}return R.length?R[0]:null},tU5=function(B,z){if(!g.yNl(B)||B.T!=null&&g.mfB(z,B.T)&&B.T.T.rawcc!=null)return!1;
z=!!B.T&&B.T.isManifestless&&Object.values(B.T.T).some(function(T){return g.a$(T,"386")});
B=!!B.T&&!B.T.isManifestless&&g.bkK(B.T);return z||B},mq=function(){dT.call(this)},XWq=function(B){var z=jaF.length;
if(B.byteLength<z)return!1;B=new Uint8Array(B,0,z);for(var T=0;T<z;T++)if(jaF[T]!==B[T])return!1;return!0},Zgh=function(B,z,T,R,h,W,b,l,w){switch(b.tagName){case "b":l.bold=!0;
break;case "i":l.italic=!0;break;case "u":l.underline=!0}for(var q=0;q<b.childNodes.length;q++){var c=b.childNodes[q];if(c.nodeType===3)c=new GA(z,T,R,h.id,c.nodeValue,W||q>0,g.Ep(l)?void 0:l),w.push(c),h.T.push(c);else{var L={};Object.assign(L,l);Zgh(B,z,T,R,h,!0,c,L,w)}}},e3F=function(B){var z=B.split(":");
B=0;z=g.d(z);for(var T=z.next();!T.done;T=z.next())B=B*60+Number(T.value);return B*1E3},saI=function(B,z,T,R){R=Object.assign({AI:0},R);
return new At(B,z,T,"_"+ak++,R)},nw=function(B,z){g.K.call(this);
this.j=B;this.dF=z;this.T=null;this.U=this.j.Tr();this.logger=new g.RH("caps")},SOP=function(B,z,T){if(typeof z==="string"||vwh(z))return[{trackData:z,
oU:T}];if(typeof z==="string"&&z.substring(0,6)==="WEBVTT"||typeof z!=="string"&&XWq(z))return[{trackData:z,oU:T}];var R=new DataView(z);if(R.byteLength<=8||R.getUint32(4)!==1718909296)return[];var h=g.juB(R);if(B.U&&h){var W=g.m_K(h),b=g.nbd(h);h=h.i9;W&&h&&B.U.Dr(h,W,b)}B=g.h8(R,1835295092);if(!B||!B.length||!B[0].size)return[];W=[];for(b=0;b<B.length;b++)h=B[b],h=new Uint8Array(z,h.dataOffset,h.size-(h.dataOffset-h.offset)),h=g.pv(h),W.push({trackData:h,oU:T+b*1E3});EwU(R,W,T);return W=W.filter(function(l){return!!l.trackData})},
EwU=function(B,z,T){var R=g.Zx(B,0,1836476516),h=9E4;
R&&(h=g.e8(R)||9E4);R=0;for(var W=g.h8(B,1836019558),b=0;b<W.length;b++){var l=W[b];b<z.length&&(l=g.Zx(B,l.dataOffset,1953653094))&&(l=g.Zx(B,l.dataOffset,1952867444))&&(l=g.Te(l)/h*1E3,b===0&&(R=l),z[b].oU=l-R+T||T*b*1E3)}},Bag=function(B,z,T){B.T||(B.T=new mq);
B=B.T.yE(z,T);Math.random()<.01&&g.KV(Error("Deprecated subtitles format in web player: WebVTT"));return B},zRP=function(B){var z={};
if(B=g.oQ(B))z.lang=B,g.OsI.test(B)&&(z.Sw=1);return z},uk=function(B){g.I$.call(this,B);
var z=this;this.j=B;this.zZ=[];this.WD={};this.Kf={};this.X=!1;this.W="NONE";this.U=this.N=this.TZ=this.IK=this.eI=null;this.O0={pX:function(){z.pX()},
Mm:function(W,b,l,w){z.Mm(W,b,l,w)}};
this.T=null;this.dF=this.j.K();this.videoData=this.j.getVideoData();this.EE=this.j.NG();this.Y={Tj:{}};this.L={Tj:{}};g.Np(this.videoData)?this.W="OFFLINE":tU5(this.videoData,this.j)?this.W="SABR_LIVE":g.nEH(this.videoData,this.j)?this.W="LIVE":this.videoData.captionTracks.length?this.W="INNERTUBE":this.videoData.XS&&(this.W="TTS");this.sE=this.dF.controlsType==="3";this.MG=new nw(this.j,this.dF);this.XE=new g.kb(this);this.J=new g.O({B:"div",G:"ytp-caption-window-container",C:{id:"ytp-caption-window-container"}});
this.UE={top:0,right:0,bottom:0,left:0,width:1,height:1};var T=null,R=g.n2("yt-html5-player-modules::subtitlesModuleData");R&&(T=new g.p2(R));this.storage=T;var h;this.aK=!((h=B.Wu())==null||!h.tp());this.V=TaW(this);this.RK=!this.V&&this.sE&&this.aK&&(this.W==="LIVE"||this.W==="SABR_LIVE");g.m(this,this.MG);this.V?this.cD=this.lO=null:(this.lO=new g.Ew(this.Y5,void 0,this),g.m(this,this.lO),this.cD=new g.Si(this.Z2E,2E3,this),g.m(this,this.cD));g.m(this,this.XE);g.Pw(this.player,this.J.element,4);
g.m(this,this.J);this.V||this.XE.Z(B,"resize",this.Wm);(this.U0=g.Po(this.dF)&&!g.Gh()&&!this.j.isFullscreen()&&!this.V&&!this.RK)&&this.XE.Z(B,"resize",this.sxF);this.XE.Z(B,"onPlaybackAudioChange",this.dSf);this.XE.Z(B,g.YQ("captions"),function(W){z.onCueRangeEnter(W)});
this.XE.Z(B,g.lu("captions"),function(W){z.onCueRangeExit(W)});
RRF(this,f0h()||{});this.player.A0("onCaptionsModuleAvailable")},bJq=function(B){if(B.dF.Yo===1||B.videoData.nC===1||g.Au(B.videoData,"yt:cc")==="alwayson")return!0;
if(B.videoData.captionTracks.length)var z=B.getAudioTrack().U;if(B.dF.Yo===2){if(g.Zf(B.dF))var T=hRq(B);else if(B.storage)try{T=B.storage.get("module-enabled")}catch(h){B.storage.remove("module-enabled")}else T=null;if(T!=null)return!!T}T=x1c(B.player.getAudioTrack(),g.Zf(B.dF));var R=g.Au(B.videoData,"yt:cc");if(WwF(B)===void 0){if(T==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return R?R==="on":!0;if(T==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return R==="on"}else return R==="on";return z==="ON"||
g.Au(B.videoData,"yt:cc")==="on"},HC=function(B,z){if(B.T&&(z===void 0||!z)||!B.videoData.captionTracks.length)return!1;
B=B.getAudioTrack();return!!B.T||B.U==="FORCED_ON"},WwF=function(B){var z=void 0,T=g.OW(g.fD(),65);
if(g.Zf(B.dF)&&T!=null){if(hRq(B)!=null)return!1;z=!T}return z},OX=function(B,z){if(!B.U)return null;
if(B.N&&B.N.W)return B.N.W;z=Ydp(B,z);z=g.h5(B.U.U,z);var T=null;if(vWF(B.dF)){var R=B.j.isInline()?void 0:g.kK("yt-player-caption-sticky-language");for(var h=[R,B.videoData.captionsLanguagePreference,B.dF.captionsLanguagePreference,g.Au(B.videoData,"yt:cc_default_lang")],W=!1,b=0;b<h.length;b++){var l=h[b];if(l){W=!0;for(var w=0;w<z.length;w++)if(g.oQ(z[w])===l)return z[w];for(w=0;w<z.length;w++)if(g.oQ(z[w]).split("-")[0]===l.split("-")[0])return z[w]}}if(W&&B.U&&(h=B.U.V,h.length))for(h=g.d(h),
W=h.next();!W.done;W=h.next())if(W=W.value,W.languageCode===R){T=W;break}}else for(R=[B.videoData.captionsLanguagePreference,B.dF.captionsLanguagePreference,g.Au(B.videoData,"yt:cc_default_lang")],h=0;h<R.length;h++)for(W=0;W<z.length;W++)if(g.oQ(z[W])===R[h])return z[W];R=null;B.N&&B.N.Y&&(R=B.N.Y);R||(R=z.find(function(q){return q.isDefault})||null);
R||(R=z[0]||fw(B));R&&T&&g.oQ(R).split("-")[0]!==T.languageCode.split("-")[0]&&(R=D1s(R,T));return R},fw=function(B){return B.N&&B.N.T},Nd=function(B){var z=fw(B);
return!!z&&B.T===z},lGp=function(B,z){var T=B.j.Wu().jk().textTracks;
B=B.T.toString();for(var R=0;R<T.length;R++){var h=T[R];h.id===B&&(z?h.mode!=="showing"&&(h.mode="showing"):h.mode==="showing"&&(h.mode="disabled"))}},ZP=function(B,z,T){B.loaded&&B.unload();
T!=null&&(B.X=T,B.X&&(g.Zf(B.dF)?tt(B,!!z):j_(B,!!z)));B.dF.D("html5_sends_cfs_after_caption_loaded")||B.dF.D("html5_sends_cfs_after_caption_parsed")?(z!==null||HC(B,!0)||Xq(B,null,z,B.X,!1),B.T=z,HC(B)&&(B.T=fw(B))):(Xq(B,B.T,z,B.X,!1),B.T=z,HC(B)&&(z=fw(B),Xq(B,B.T,z,B.X,!0),B.T=z));var R;wy5(B,(R=B.T)!=null?R:void 0);B.load()},iJR=function(B,z){if(z instanceof At){var T=B.WD[z.id];
T&&T.U!==z&&(T.dispose(),delete B.WD[z.id],T=null);T||(T=qdR(B,z))&&(B.WD[z.id]=T)}else T=z.windowId,B.Kf[T]||(B.Kf[T]=[]),B.Kf[T].push(z)},qdR=function(B,z){var T=cps(B);
if(!T)return null;var R=B.T?g.oQ(B.T):null;R&&g.OsI.test(R)&&(z.params.Sw=1);var h=B.EE.getPlayerSize();R=h.height*B.UE.height;h=h.width*B.UE.width;B.dF.playerStyle!=="google-live"||B.Y.isDefault||Object.assign(z.params,B.Y);switch(z.params.AI!=null?z.params.AI:z.T.length>1?1:0){case 1:return new PC(z,B.Y,B.L,T.width,T.height,h,R,B.dF.experiments,B.IN.bind(B),B.j);case 2:return new Kw(z,B.Y,B.L,T.width,T.height,h,R,B.dF.experiments,B.IN.bind(B),B.j);default:return new qd(z,B.Y,B.L,T.width,T.height,
h,R,B.dF.experiments,B.IN.bind(B),B.j)}},RRF=function(B,z,T){T=T===void 0?!1:T;
var R=e_.Tj;B.Y={};Object.assign(B.Y,e_);B.Y.Tj={};Object.assign(B.Y.Tj,R);B.L={Tj:{}};var h=z.backgroundOverride?B.L:B.Y,W=z.background||R.background;ys.test(W);h.Tj.background=W;h=z.colorOverride?B.L:B.Y;W=z.color||R.color;ys.test(W);h.Tj.color=W;h=z.windowColorOverride?B.L:B.Y;W=z.windowColor||e_.windowColor;ys.test(W);h.windowColor=W;h=z.backgroundOpacityOverride?B.L:B.Y;W=z.backgroundOpacity;W==null&&(W=R.backgroundOpacity);h.Tj.backgroundOpacity=W;h=z.fontSizeIncrementOverride?B.L:B.Y;W=z.fontSizeIncrement;
W==null&&(W=R.fontSizeIncrement);h.Tj.fontSizeIncrement=W;W=z.fontStyleOverride?B.L:B.Y;h=z.fontStyle;h==null&&(h=R.bold&&R.italic?3:R.bold?1:R.italic?2:0);W=W.Tj;switch(h){case 1:W.bold=!0;delete W.italic;break;case 2:delete W.bold;W.italic=!0;break;case 3:W.bold=!0;W.italic=!0;break;default:delete W.bold,delete W.italic}h=z.textOpacityOverride?B.L:B.Y;W=z.textOpacity;W==null&&(W=R.textOpacity);h.Tj.textOpacity=W;h=z.windowOpacityOverride?B.L:B.Y;W=z.windowOpacity;W==null&&(W=e_.windowOpacity);h.windowOpacity=
W;h=z.charEdgeStyleOverride?B.L:B.Y;W=z.charEdgeStyle;W==null&&(W=R.charEdgeStyle);h.Tj.charEdgeStyle=W;h=z.fontFamilyOverride?B.L:B.Y;W=z.fontFamily;W==null&&(W=R.fontFamily);h.Tj.fontFamily=W;B.loaded&&B.Wm();T&&g.D_("yt-player-caption-display-settings",z,2592E3)},Lw7=function(B,z){if(!B.U)return{};
if(z){g.Ep(z)||B.fp(z.vss_id,"m");if(B.V||!g.zU(z))return;if(g.Ep(z)){ZP(B,null,!0);return}for(var T,R=g.h5(B.U.U,!0),h=0;h<R.length;h++){var W=R[h];W.languageCode!==z.languageCode||T&&(W.languageName!==z.languageName||(W.captionId||"")!==(z.captionId||"")||g.Cb(W)!==z.displayName)||(T=z.translationLanguage?D1s(W,z.translationLanguage):W)}B.Qq(z.position);!T||T===B.T&&B.loaded||(z=g.jP(),R=g.oQ(T),z.length&&R===z[z.length-1]||(z.push(R),g.D_("yt-player-caption-language-preferences",z)),vWF(B.dF)&&
!B.j.isInline()&&g.D_("yt-player-caption-sticky-language",R,2592E3),ZP(B,T,!0))}else return B.loaded&&B.T&&!Nd(B)?g.ro(B.T):{};return""},rps=function(B,z,T){z&&!B.TZ?(z=gwc({Sw:0,
lang:"en"}),B.TZ=[z,new GA(z.start,z.end-z.start,0,z.id,T!=null?T:"Captions look like this")],B.player.A$(B.TZ)):!z&&B.TZ&&(C3F(B,B.TZ),B.TZ=null)},C3F=function(B,z){B.player.w2(z);
z=g.d(z);for(var T=z.next();!T.done;T=z.next())g.GU(B.zZ,T.value);YM(B.lO)},wy5=function(B,z){B.dF.D("html5_modify_caption_vss_logging")&&(B.videoData.gC=z)},cps=function(B){var z=B.EE.getVideoContentRect(!0).height,T=B.EE.getVideoContentRect(!0).width;
if(!z||!T)return null;z*=B.UE.height;T*=B.UE.width;return{width:T,height:z}},j_=function(B,z){if(B.storage)try{B.storage.set("module-enabled",z)}catch(T){}},tt=function(B,z){B.j.isInline()||g.D_("yt-player-sticky-caption",z,2592E3)},hRq=function(B){if(!B.j.isInline())return g.kK("yt-player-sticky-caption")},TaW=function(B){var z,T=!((z=B.j.Wu())==null||!z.G_());
return B.sE&&T&&B.W!=="LIVE"&&B.W!=="SABR_LIVE"},Ydp=function(B,z){g.vx(B.videoData)&&(z=!0);
z||(z=B.W==="TTS"?!1:B.W==="INNERTUBE"?!1:!0);return z||B.dF.D("web_deprecate_always_includes_asr_setting")&&g.Zf(B.dF)?!0:!!g.OW(g.fD(),66)},Xq=function(B,z,T,R,h){B.dF.D("html5_sends_cfs_after_caption_loaded")||B.dF.D("html5_sends_cfs_after_caption_parsed")?B.SZ(T,!!T,h?"g":R?"m":"s"):h?B.SZ(T,!0,"g"):R?z?B.SZ(T,!!T,"m"):T&&B.SZ(T,!0,"m"):!z&&T&&B.SZ(T,!0,"s")};
g.dh.prototype.XV=g.bd(77,function(){return!1});
g.dh.prototype.Wq=g.bd(76,function(){});
g.A5.prototype.Wq=g.bd(75,function(B,z,T){var R=this;this.xd();z=this.f6(B,z);var h=this.Lf.K().D("html5_report_captions_ctmp_qoe"),W=(0,g.f)();this.Sb();P$R(this,z,{format:"RAW",onSuccess:function(b){R.T=null;if(h){var l=(b.responseText.length/1024).toFixed(),w=(0,g.f)();R.videoData.OE("capresp",{ms:w-W,kb:l})}T.Mm(b.responseText,B)},
onError:h?function(b){var l;b=(l=b==null?void 0:b.status)!=null?l:0;R.videoData.OE("capfail",{status:b})}:void 0,
withCredentials:!0})});
g.Uk.prototype.Wq=g.bd(74,function(B,z,T){var R=this;this.xd();z=this.f6(B,z);this.Sb();this.T=g.yH(z,{format:"RAW",onSuccess:function(h){R.T=null;T.Mm(h.responseText,B)},
withCredentials:!0})});
g.Xe.prototype.R4=g.bd(73,function(){for(var B=g.Nu(document,"track",void 0,this.T),z=0;z<B.length;z++)g.RK(B[z])});
g.xE.prototype.R4=g.bd(72,function(){this.mediaElement.R4()});
g.Xe.prototype.tp=g.bd(71,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.xE.prototype.tp=g.bd(70,function(){return this.mediaElement.tp()});
g.Xe.prototype.G_=g.bd(69,function(){return!!this.T.textTracks});
g.xE.prototype.G_=g.bd(68,function(){return this.mediaElement.G_()});
g.Xe.prototype.ZT=g.bd(67,function(B){for(var z=0;z<B.length;z++)this.T.appendChild(B[z])});
g.xE.prototype.ZT=g.bd(66,function(B){this.mediaElement.ZT(B)});
g.Er.prototype.Dr=g.bd(65,function(B,z,T){this.KF.Dr(B,z,T)});
g.j$.prototype.Dr=g.bd(64,function(B,z,T){this.U.set(B,{PT:z,hP:T})});
g.XX.prototype.Dr=g.bd(63,function(B,z,T){this.zZ.Dr(B,z,T)});
g.Er.prototype.Z3=g.bd(62,function(B){return this.KF.Z3(B)});
g.XX.prototype.Z3=g.bd(61,function(B){var z=2;this.N.has(B)?z=0:g.P4Y(this,B)&&(z=1);return z});
g.M2.prototype.zX=g.bd(49,function(B){var z=this.app.t$({playerType:void 0});return z?z.zX(B):!1});
g.ml.prototype.zX=g.bd(48,function(B){return this.iO.GR.zX(B)});
g.DW.prototype.zX=g.bd(47,function(B){return this.Zn().some(function(z){return z.namespace===B})});
g.mU.prototype.zX=g.bd(46,function(){return!1});
g.M2.prototype.fp=g.bd(44,function(B,z){this.app.Ji().fp(B,z)});
g.ml.prototype.fp=g.bd(43,function(B,z){this.iO.fp(B,z)});
g.og.prototype.fp=g.bd(42,function(B,z){B=[B,z];g.r9(this,g.sr(this.provider),"cfi",B)});
g.$7.prototype.fp=g.bd(41,function(B,z){this.qoe&&this.qoe.fp(B,z)});
g.WB.prototype.fp=g.bd(40,function(B,z){this.K4().fp(B,z)});
g.mU.prototype.fp=g.bd(39,function(){});
g.M2.prototype.SZ=g.bd(38,function(B,z,T){this.app.Ji().SZ(B,z,T)});
g.ml.prototype.SZ=g.bd(37,function(B,z,T){this.iO.SZ(B,z,T)});
g.og.prototype.SZ=g.bd(36,function(B,z,T){if(this.lO!==B||this.JZ!==z)z=z==="rawcc"?"":z,T=[B,z,this.lO,T],g.r9(this,g.sr(this.provider),"cfs",T),this.lO=B,this.JZ=z});
g.$7.prototype.SZ=g.bd(35,function(B,z,T){this.qoe&&this.qoe.SZ(B,z,T)});
g.WB.prototype.SZ=g.bd(34,function(B,z,T){this.K4().SZ(B,z,T)});
g.mU.prototype.SZ=g.bd(33,function(){});
g.Z3.prototype.a6=g.bd(20,function(){return this.TZ});
g.ob.prototype.a6=g.bd(19,function(){return this.Ji().Tr()});
g.M2.prototype.Tr=g.bd(18,function(){return this.app.a6()});
g.ml.prototype.Tr=g.bd(17,function(){return this.iO.Tr()});
g.WB.prototype.Tr=g.bd(16,function(){var B;return((B=this.loader)==null?void 0:B.a6())||null});
g.mU.prototype.Tr=g.bd(15,function(){return null});
g.vK.prototype.zS=g.bd(1,function(B){return(B=this.w_(B))?B.T:0});
g.iP.prototype.zS=g.bd(0,function(){return 0});
var nWP=/#(.)(.)(.)/,m1c=/^#(?:[0-9a-f]{3}){1,2}$/i,XDg={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};lk.prototype.contains=function(B){B=g.$P(this.segments,B);return B>=0||B<0&&(-B-1)%2===1};
lk.prototype.length=function(){return this.segments.length/2};
g.G(NqR,g.K);g.I=NqR.prototype;g.I.gF=function(){g.K.prototype.gF.call(this);this.Y&&this.Y.cancel()};
g.I.k_=function(){this.seekTo(this.player.getCurrentTime())};
g.I.seekTo=function(B){B-=this.player.p4();var z=this.T;this.T=g.c7(this.TZ.uL(B).oK);z!==this.T&&this.N&&this.N()};
g.I.reset=function(){this.W=new lk;this.X=-1;this.Y&&(this.Y.cancel(),this.Y=null)};
g.I.YU=function(){this.xd();var B;if(B=this.T!=null)B=this.T,B=B.T.bL(B);if(B&&!this.Y&&!(this.T&&this.T.startTime-this.player.getCurrentTime()>30)){B=this.T;B=B.T.dC(B);var z=B.oK[0],T;if((T=this.player.getVideoData())==null?0:T.enableServerStitchedDai)if(T=this.player.Tr()){var R=z.T.info.id,h=z.FE,W=B.oK[0].W;if(this.policy.zZ){if(T=T.ya(W,h,R,3))B.W=T}else if(R=T.sA(W,h,R,3))if(T=T.Z3(h),T===0)R&&(B.T=new g.QP(R));else if(T===2){this.L.start();tKh(this)&&this.seekTo(this.player.getCurrentTime());
return}}z.T.index.bZ(z.FE)?(this.W.contains(B.oK[0].FE)||jFh(this,B),this.T=g.c7(B.oK)):tKh(this)&&this.seekTo(this.player.getCurrentTime())}this.L.start()};
g.G(wT,g.dh);g.I=wT.prototype;g.I.Wq=function(B,z,T){var R=this;this.Sb();z=e5R(this,B.getId());z||(z=B.languageCode,z=this.T.isManifestless?sFh(this,z,"386"):sFh(this,z));if(z){var h=(z.index.zS(z.index.dY())-z.index.getStartTime(z.index.dY()))*1E3,W=this.j.K(),b=new g.CqK(W),l=function(){R.Y&&R.Y.reset();R.X=!0};
W.D("html5_keep_caption_data_after_seek")&&(l=null);this.Y=new NqR(b,this.j,z,function(w,q){T.Mm(w,B,q,h)},this.L||g.Ez(z.info),l)}};
g.I.XV=function(){var B=this.X;this.X=!1;return B};
g.I.nK=function(B){var z=this.j.K().D("html5_fallback_if_rawcc_missing");var T=this.T.T.rawcc!=null;if(!this.L||!T&&z)z=this.T.isManifestless?Zep(this,"386"):Zep(this);else{if(!T){this.logger.T(386248249,"rawcc used but unavailable");return}z=[new g.Lb({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.Lb({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}z=g.d(z);
for(T=z.next();!T.done;T=z.next())g.G9(this.U,T.value);B.pX()};
g.I.Sb=function(){this.Y&&(this.Y.dispose(),this.Y=null)};
g.I.f6=function(){return""};
g.I.g4=function(){this.Y&&(this.Y.reset(),this.j.I7("captions"))};
var ys=/^#(?:[0-9a-f]{3}){1,2}$/i;var BgF=["left","right","center","justify"];g.G(qd,g.O);g.I=qd.prototype;g.I.bE=function(B,z){this.sE=B;this.MG=z;var T=g.x6(this.element,this.element.parentElement);this.eI=B-T.x;this.EE=z-T.y};
g.I.W9=function(B,z){if(B!==this.sE||z!==this.MG){g.lH(this.element,"ytp-dragging")||g.ww(this.element,"ytp-dragging");var T=g.Dk(this.element);B=B-this.eI-.02*this.II;var R=z-this.EE-.02*this.C4,h=(B+T.width/2)/this.maxWidth*3;h=Math.floor(g.yQ(h,0,2));var W=(R+T.height/2)/this.maxHeight*3;W=Math.floor(g.yQ(W,0,2));z=h+W*3;B=(B+h/2*T.width)/this.maxWidth;B=g.yQ(B,0,1)*100;T=(R+W/2*T.height)/this.maxHeight;T=g.yQ(T,0,1)*100;this.U.params.qL=z;this.U.params.pU=T;this.U.params.mX=B;this.U.params.isDefault=
!1;this.T.qL=z;this.T.pU=T;this.T.mX=B;this.T.isDefault=!1;this.UE.qL=z;this.UE.pU=T;this.UE.mX=B;this.UE.isDefault=!1;this.x8()}};
g.I.QR=function(){g.iH(this.element,"ytp-dragging")};
g.I.x8=function(){this.Nb(this.L)};
g.I.Nb=function(B){var z=this.aK?0:Math.min(this.x4(),this.maxWidth),T=this.zP(),R=this.aK;if(R){var h=getComputedStyle(this.W.parentNode);h=ik(h.borderLeftWidth)+ik(h.borderRightWidth)+ik(h.paddingLeft)+ik(h.paddingRight)}else h=0;var W=h;h="";this.U.params.Sw===3&&(h="rotate(180deg)");var b=R?"calc(96% - "+W+"px)":"96%";g.Ml(this.element,{top:0,left:0,right:"",bottom:"",width:z?z+"px":"",height:T?T+"px":"","max-width":b,"max-height":b,margin:"",transform:""});this.xN(B);h={transform:h,top:"",left:"",
width:z?z+"px":"",height:T?T+"px":"","max-width":"","max-height":""};var l=this.T.mX*.96+2;b=this.T.qL;switch(b){case 0:case 3:case 6:(R=this.T.Tj.fontSizeIncrement)&&R>0&&this.T.Sw!==2&&this.T.Sw!==3&&(l=Math.max(l/(1+R*2),2));h.left=l+"%";break;case 1:case 4:case 7:h.left=l+"%";l=this.W.offsetWidth;z||l?(z=z||l+1,h.width=z+"px",h["margin-left"]=R?z/-2-W/2+"px":z/-2+"px"):h.transform+=" translateX(-50%)";break;case 2:case 5:case 8:h.right=100-l+"%"}R=this.T.pU*.96+2;switch(b){case 0:case 1:case 2:h.top=
R+"%";break;case 3:case 4:case 5:h.top=R+"%";(T=T||this.element.clientHeight)?(h.height=T+"px",h["margin-top"]=T/-2+"px"):h.transform+=" translateY(-50%)";break;case 6:case 7:case 8:h.bottom=100-R+"%"}g.Ml(this.element,h);if(this.X){T=this.W.offsetHeight;R=1;for(z=0;z<B.length;z++)h=B[z],typeof h.text==="string"&&(R+=h.text.split("\n").length-1,h.append||z===0||R++);T/=R;this.X.style.height=T+"px";this.X.style.width=T+"px";this.element.style.paddingLeft=T+5+"px";this.element.style.paddingRight=T+
5+"px";B=Number(this.element.style.marginLeft.replace("px",""))-T-5;T=Number(this.element.style.marginRight.replace("px",""))-T-5;this.element.style.marginLeft=B+"px";this.element.style.marginRight=T+"px"}};
g.I.xN=function(B){var z;for(z=0;z<B.length&&B[z]===this.L[z];z++);if(this.XE||this.L.length>z)z=0,this.XE=!1,this.L=[],this.J=this.lO=this.zZ=null,g.zJ(this.W);for(;z<B.length;z++)W97(this,B[z])};
g.I.x4=function(){return 0};
g.I.zP=function(){return 0};
g.I.toString=function(){return g.O.prototype.toString.call(this)};YOW.prototype.clear=function(){this.Y=this.time=this.mode=0;this.T=[];this.reset()};
YOW.prototype.reset=function(){this.mode=0;this.W.reset(0);this.V.reset(1)};
var lpP=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];cC.prototype.set=function(B){this.type=B};
cC.prototype.get=function(){return this.type};
Lw.prototype.clear=function(){this.state=0};
Lw.prototype.update=function(){this.state=this.state===2?1:0};
Lw.prototype.u1=function(){return this.state!==0};
Lw.prototype.matches=function(B,z){return this.u1()&&B===this.gT&&z===this.n6};
L9W.prototype.reset=function(){this.timestamp=this.T=0};
Cw.prototype.updateTime=function(B){for(var z=1;z<=15;++z)for(var T=1;T<=32;++T)this.Y[z][T].timestamp=B};
Cw.prototype.debugString=function(){for(var B="\n",z=1;z<=15;++z){for(var T=1;T<=32;++T){var R=this.Y[z][T];B=R.T===0?B+"_":B+String.fromCharCode(R.T)}B+="\n"}return B};
Cw.prototype.reset=function(B){for(var z=0;z<=15;z++)for(var T=0;T<=32;T++)this.Y[z][T].reset();this.W=B;this.T=0;this.U=this.row=1};
var CMW=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],r4P=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],owq=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],F9c=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];A4W.prototype.reset=function(B,z){this.V=z;this.style.set(2);this.U=this.X;this.W=this.L;this.T=this.U;var T=(B<<2)+(z<<1);this.X.reset(T);this.L.reset(T);this.text.reset((B<<2)+(z<<1)+1)};
bgg.prototype.reset=function(B){this.V=B;this.U.clear();this.W=this.Y;this.Y.reset(B,0);this.X.reset(B,1)};VUK.prototype.W=function(){};g.G(GA,g.Wj);GA.prototype.toString=function(){return g.Wj.prototype.toString.call(this)};g.G(dT,g.K);dT.prototype.yE=function(){return[]};
dT.prototype.reset=function(){};g.G(At,g.Wj);At.prototype.toString=function(){return g.Wj.prototype.toString.call(this)};
var ak=0;g.G(UX,dT);UX.prototype.reset=function(){this.X={};this.U=this.T=null;this.V=!0};
UX.prototype.yE=function(B,z){B=B.firstChild;B.getAttribute("format");z=z||0;Number.isFinite(z);B=Array.from(B.childNodes);B=g.d(B);for(var T=B.next();!T.done;T=B.next())if(T=T.value,T.nodeType===1)switch(T.tagName){case "head":var R=T;break;case "body":var h=T}if(R)for(R=Array.from(R.childNodes),R=g.d(R),B=R.next();!B.done;B=R.next())if(B=B.value,B.nodeType===1)switch(B.tagName){case "pen":T=B.getAttribute("id");var W=this.pens,b={},l=B.getAttribute("p");l&&Object.assign(b,this.pens[l]);l=Vs(B,"b");
l!=null&&(b.bold=l);l=Vs(B,"i");l!=null&&(b.italic=l);l=Vs(B,"u");l!=null&&(b.underline=l);l=Qs(B,"et");l!=null&&(b.charEdgeStyle=l);l=Qs(B,"of");l!=null&&(b.offset=l);l=gT(B,"bc");l!=null&&(b.background=l);l=gT(B,"ec");l!=null&&(b.Cz=l);l=gT(B,"fc");l!=null&&(b.color=l);l=Qs(B,"fs");l!=null&&l!==0&&(b.fontFamily=l);l=Md(B,"sz");l!==void 0&&(b.fontSizeIncrement=l/100-1);l=Md(B,"bo");l!==void 0&&(b.backgroundOpacity=l/255);l=Md(B,"fo");l!==void 0&&(b.textOpacity=l/255);l=Qs(B,"rb");l!=null&&l!==10&&
l!==0&&(b.DR=l>10?l-1:l);B=Qs(B,"hg");B!=null&&(b.X$=B);W[T]=b;break;case "ws":T=B.getAttribute("id");this.J[T]=J4F(this,B);break;case "wp":T=B.getAttribute("id"),this.L[T]=pWh(this,B)}if(h){R=[];h=Array.from(h.childNodes);h=g.d(h);for(B=h.next();!B.done;B=h.next())if(B=B.value,B.nodeType===1)switch(B.tagName){case "w":this.T=$aF(this,B,z,!1);(B=this.X[this.T.id])&&B.end>this.T.start&&(B.end=this.T.start);this.X[this.T.id]=this.T;R.push(this.T);break;case "p":var w=B;l=z;T=[];W=w.getAttribute("w")||
this.W;b=!!Vs(w,"a");l=(Md(w,"t")||0)+l;var q=Md(w,"d")||5E3;b||(!this.V&&this.U&&this.U.windowId===W&&this.U.end>l&&(this.U.end=l),this.U&&this.U.text==="\n"&&(this.U.text=""));var c=b?6:5,L=w.getAttribute("p");L=L?this.pens[L]:null;var C=Array.from(w.childNodes);C.length&&(this.V=w.getAttribute("d")!=null);for(w=0;w<C.length;w++){var r=C[w],F=void 0;w>0&&(b=!0);var A=void 0;r.nodeType===1&&(A=r);if(A&&A.tagName==="s"){if((r=(r=A.getAttribute("p"))?this.pens[r]:null)&&r.DR&&(r.DR===1?(r=C.slice(w,
w+4),r.length===4&&(F=y4P(l,q,W,b,c,r,this.pens),w+=3)):F=y4P(l,q,W,b,c,[A],this.pens)),!F){var a=A;F=l;A=q;r=W;var V=b,M=c,x=a.textContent?a.textContent:"",v=a.getAttribute("p");v=v?this.pens[v]:null;a=Md(a,"t")||0;F=new GA(F+a,A-a,M,r,x,V,v)}}else F=new GA(l,q,c,W,r.textContent||"",b,L);T.push(F);this.U=F}if(T.length>0)for(T[0].windowId===this.W&&(this.T=$aF(this,B,z,!0),R.push(this.T)),B=g.d(T),T=B.next();!T.done;T=B.next())T=T.value,T.windowId=this.T.id,this.T.T.push(T),R.push(T)}z=R}else z=[];
return z};var oAs=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.G(Jt,dT);Jt.prototype.reset=function(){this.U.clear()};
Jt.prototype.yE=function(B,z){var T=JSON.parse(B);if(!T)return[];if(T.pens){B=0;for(var R=g.d(T.pens),h=R.next();!h.done;h=R.next()){h=h.value;var W={},b=h.pParentId;b&&Object.assign(W,this.T.get(b));h.bAttr&&(W.bold=!0);h.iAttr&&(W.italic=!0);h.uAttr&&(W.underline=!0);b=h.ofOffset;b!=null&&(W.offset=b);h.szPenSize!==void 0&&(W.fontSizeIncrement=h.szPenSize/100-1);b=h.etEdgeType;b!=null&&(W.charEdgeStyle=b);h.ecEdgeColor!==void 0&&(W.Cz=pw(h.ecEdgeColor));b=h.fsFontStyle;b!=null&&b!==0&&(W.fontFamily=
b);h.fcForeColor!==void 0&&(W.color=pw(h.fcForeColor));h.foForeAlpha!==void 0&&(W.textOpacity=h.foForeAlpha/255);h.bcBackColor!==void 0&&(W.background=pw(h.bcBackColor));h.boBackAlpha!==void 0&&(W.backgroundOpacity=h.boBackAlpha/255);(b=h.rbRuby)&&b!==10&&(W.DR=b>10?b-1:b,W.textEmphasis=oAs.get(W.DR));h.hgHorizGroup&&(W.X$=h.hgHorizGroup);this.T.set(B++,W)}}if(T.wsWinStyles)for(B=0,R=g.d(T.wsWinStyles),h=R.next();!h.done;h=R.next())h=h.value,W={},(b=h.wsParentId)?Object.assign(W,this.W.get(b)):Object.assign(W,
this.V),h.mhModeHint!==void 0&&(W.AI=h.mhModeHint),h.juJustifCode!==void 0&&(W.textAlign=h.juJustifCode),h.pdPrintDir!==void 0&&(W.Sw=h.pdPrintDir),h.sdScrollDir!==void 0&&(W.AX=h.sdScrollDir),h.wfcWinFillColor!==void 0&&(W.windowColor=pw(h.wfcWinFillColor)),h.wfoWinFillAlpha!==void 0&&(W.windowOpacity=h.wfoWinFillAlpha/255),this.W.set(B++,W);if(T.wpWinPositions)for(B=0,R=g.d(T.wpWinPositions),h=R.next();!h.done;h=R.next())h=h.value,W={},(b=h.wpParentId)&&Object.assign(W,this.Y.get(b)),h.ahHorPos!==
void 0&&(W.mX=h.ahHorPos),h.apPoint!==void 0&&(W.qL=h.apPoint),h.avVerPos!==void 0&&(W.pU=h.avVerPos),h.ccCols!==void 0&&(W.zI=h.ccCols),h.rcRows!==void 0&&(W.Jb=h.rcRows),this.Y.set(B++,W);if(T.events){B=[];T=g.d(T.events);for(R=T.next();!R.done;R=T.next()){var l=R.value;h=(l.tStartMs||0)+z;W=l.dDurationMs||0;if(l.id)b=String(l.id),R=PMq(this,l,h,W,b),B.push(R),this.U.set(b,R);else{l.wWinId?b=l.wWinId.toString():(b="_"+ak++,R=PMq(this,l,h,W,b),B.push(R),this.U.set(b,R));R=B;var w=l;W===0&&(W=5E3);
l=this.U.get(b);var q=!!w.aAppend,c=q?6:5,L=w.segs,C=null;w.pPenId&&(C=this.T.get(w.pPenId));for(w=0;w<L.length;w++){var r=L[w],F=r.utf8;if(F){var A=r.tOffsetMs||0,a=null;r.pPenId&&(a=this.T.get(r.pPenId));if((l.params.AI!=null?l.params.AI:l.T.length>1?1:0)===2&&q&&F==="\n")continue;r=null;var V=[],M;if(M=a&&a.DR===1){M=L;var x=w;if(x+3>=M.length||!M[x+1].pPenId||!M[x+2].pPenId||!M[x+3].pPenId)M=!1;else{var v=M[x+1].pPenId;(v=this.T.get(v))&&v.DR&&v.DR===2?(v=M[x+2].pPenId,v=this.T.get(v),!v||!v.DR||
v.DR<3?M=!1:(v=M[x+3].pPenId,M=(v=this.T.get(v))&&v.DR&&v.DR===2?!0:!1)):M=!1}}if(M)A=L[w+1].utf8,r=L[w+3].utf8,M=L[w+2].utf8,x=this.T.get(L[w+2].pPenId),F=QaW(F,A,M,r,x),r=new GA(h,W,c,b,F,q,a),w+=3;else{if(F.indexOf("<")>-1){var n=void 0;V=a;M=C;x=h;v=W;var Z=A,N=c,TP=q,hK=[],zP=g.ZQ("<html>"+F+"</html>");if(!zP.getElementsByTagName("parsererror").length&&((n=zP.firstChild)==null?0:n.childNodes.length))for(n=g.d(zP.firstChild.childNodes),zP=n.next();!zP.done;zP=n.next()){zP=zP.value;var ld=void 0,
t=void 0,UH=(t=(ld=zP.textContent)==null?void 0:ld.replace(/\n/g,""))!=null?t:"";if(zP.nodeType!==3||UH&&UH.match(/^ *$/)==null){ld={};Object.assign(ld,V||M);t=void 0;switch((t=zP)==null?void 0:t.tagName){case "b":ld.bold=!0;break;case "i":ld.italic=!0;break;case "u":ld.underline=!0}hK.push(new GA(x+Z,v-Z,N,l.id,UH,TP,ld))}}V=hK}V.length||(V=[new GA(h+A,W-A,c,l.id,F,q,a||C)])}if(V.length)for(q=g.d(V),a=q.next();!a.done;a=q.next())a=a.value,R.push(a),l.T.push(a);else r&&(R.push(r),l.T.push(r))}q=!0}}}z=
B}else z=[];return z};g.G($M,g.dh);$M.prototype.Wq=function(B,z,T){Kbp(this.videoData.videoId,B.vssId,T.Mm)};
$M.prototype.nK=function(B){if(this.audioTrack)for(var z=g.d(this.audioTrack.captionTracks),T=z.next();!T.done;T=z.next())g.G9(this.U,T.value);B.pX()};g.G(PC,qd);PC.prototype.xN=function(B){var z=this.U.T;qd.prototype.xN.call(this,B);for(B=B.length;B<z.length;B++){var T=z[B];if(W&&T.T===h)var R=W;else{R={};Object.assign(R,T.T);Object.assign(R,Fwc);var h=T.T;var W=R}W97(this,T,R)}};
var Fwc={ym:!0};g.G(xM,VUK);xM.prototype.W=function(B,z,T,R,h){if(T<R){var W="_"+ak++;T=T/1E3-this.X;R=R/1E3-this.X;B=new At(T,R-T,5,W,{textAlign:0,qL:0,mX:z*2.5,pU:B*5.33});h=new GA(T,R-T,5,W,h);this.U.push(B);this.U.push(h)}};
g.G(kM,dT);kM.prototype.yE=function(B){B=new xM(B,B.byteLength,this.U);if(xaI(B)){for(;B.byteOffset<B.T.byteLength;)for(B.version===0?B.Y=DP(B)*(1E3/45):B.version===1&&(B.Y=DP(B)*4294967296+DP(B)),B.V=vC(B);B.V>0;B.V--){var z=vC(B),T=vC(B),R=vC(B);z&4&&(z&3)===this.track&&(this.track===0||this.track===1)&&(z=this.T,z.T.push({time:B.Y,type:this.track,Vp:T,D2:R,order:z.T.length}))}c4c(this.T,B);return B.U}return[]};
kM.prototype.reset=function(){this.T.clear()};g.G(Kw,qd);g.I=Kw.prototype;g.I.x8=function(){g.zE(this.O0)};
g.I.KO=function(){this.element.removeEventListener("transitionend",this.KO,!1);g.iH(this.element,"ytp-rollup-mode");this.Nb(this.ra,!0)};
g.I.zP=function(){return this.Y?this.TZ:this.N};
g.I.x4=function(){return this.Y?this.N:this.TZ};
g.I.Nb=function(B,z){this.ra=B;if(this.U.params.Jb){for(var T=0,R=0;R<this.L.length&&T<B.length;R++)this.L[R]===B[T]&&T++;T>0&&T<B.length&&(B=this.L.concat(B.slice(T)));this.U0=this.TZ;this.N=this.TZ=0;qd.prototype.Nb.call(this,B);K9F(this,z)}qd.prototype.Nb.call(this,B)};mac.prototype.unload=function(){this.T!=null&&(this.j.removeEventListener("sabrCaptionsDataLoaded",this.T),this.T=null);this.Tz=[];this.j.publish("sabrCaptionsBufferedRangesUpdated",this.Tz)};
mac.prototype.uj=function(B){return{formatId:g.Bn(B.info.T.info,this.PB),FE:B.info.FE+(this.PB?0:1),startTimeMs:B.info.W*1E3,durationMs:B.info.L*1E3}};g.G(fpI,g.dh);g.I=fpI.prototype;g.I.Wq=function(B,z,T){this.Sb();z=B.getId();z=z!=null&&z in this.T.T?this.T.T[z]:null;z||(z=B.languageCode,z=this.T.isManifestless?Ngp(this,z,"386"):Ngp(this,z));z&&(this.Y=B,this.X=z,Hg7(this.L,T),this.j.publish("sabrCaptionsTrackChanged",g.Bn(z.info,this.T.PB)))};
g.I.nK=function(B){var z=this.T.isManifestless?OgP(this,"386"):OgP(this);z=g.d(z);for(var T=z.next();!T.done;T=z.next())g.G9(this.U,T.value);B.pX()};
g.I.Sb=function(){this.Y&&(this.Y=this.X=null,this.L.unload(),this.j.publish("sabrCaptionsTrackChanged",null))};
g.I.f6=function(){return""};
g.I.g4=function(){this.j.I7("captions")};var jaF="WEBVTT".split("").map(function(B){return B.charCodeAt(0)});
g.G(mq,dT);
mq.prototype.yE=function(B,z){B instanceof ArrayBuffer&&(B=g.pv(new Uint8Array(B)));var T=[];B=B.split(IGp);for(var R=1;R<B.length;R++){var h=B[R],W=z;if(h!==""&&!GKs.test(h)){var b=dic.exec(h);if(b&&b.length>=4){var l=e3F(b[1]),w=e3F(b[2])-l;l+=W;var q=(b=b[3])?b.split(" "):[];b={};var c=null;var L="";var C=null,r="";q=g.d(q);for(var F=q.next();!F.done;F=q.next())if(F=F.value.split(":"),F.length===2){var A=F[1];switch(F[0]){case "line":F=A.split(",");F[0].endsWith("%")&&(c=F[0],b.pU=Number.parseInt(c,10),
F.length===2&&(L=F[1].trim()));break;case "position":F=A.split(",");C=F[0];b.mX=Number.parseInt(C,10);F.length===2&&(r=F[1].trim());break;case "align":switch(A){case "start":b.textAlign=0;break;case "middle":b.textAlign=2;break;case "end":b.textAlign=1}}}c||L||(L="end");if(!C)switch(b.textAlign){case 0:b.mX=0;break;case 1:b.mX=100;break;case 2:b.mX=50}if(b.textAlign!=null){c=0;switch(L){case "center":c+=3;break;case "end":c+=6;break;default:c+=0}switch(r){case "line-left":c+=0;break;case "center":c+=
1;break;case "line-right":c+=2;break;default:switch(b.textAlign){case 0:c+=0;break;case 2:c+=1;break;case 1:c+=2}}L=c<0||c>8?7:c;b.qL=L}h=h.substring(dic.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");r=b;b=h;h={};if(b.indexOf("<")<0&&b.indexOf("&")<0)W=saI(l,w,5,r),w=new GA(l,w,5,W.id,b,!1,g.Ep(h)?void 0:h),T.push(W),T.push(w),W.T.push(w);else for(L=b.split(Apq),L.length===1?(b=5,r=saI(l,w,b,r)):(c=b=6,r=Object.assign({zI:32},r),r=new At(l,w,c,"_"+ak++,r)),T.push(r),c=l,C=0;C<L.length;C++)q=L[C],
C%2===0?(F=g.ZQ("<html>"+q+"</html>"),F.getElementsByTagName("parsererror").length?(A=F.createElement("span"),A.appendChild(F.createTextNode(q))):A=F.firstChild,Zgh(this,c,w-(c-l),b,r,C>0,A,h,T)):c=e3F(q)+W}dic.lastIndex=0}}return T};
var GKs=/^NOTE/,IGp=/(?:\r\n|\r|\n){2,}/,dic=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),Apq=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.vd.N9(mq,{yE:"wvppt"});g.G(nw,g.K);
nw.prototype.yE=function(B,z,T,R){R=R||0;T=SOP(this,B,T||0);B=[];try{for(var h=g.d(T),W=h.next();!W.done;W=h.next()){var b=W.value,l=b.trackData,w=b.oU,q=this.dF.D("safari_live_drm_captions_fix");if(typeof l!=="string"){T=B;var c=T.concat;if(q&&XWq(l))var L=Bag(this,l,w);else{var C=z,r=l,F=w,A=R;if(!vwh(r))throw Error("Invalid binary caption track data");this.T||(this.T=new kM(A,C));L=this.T.yE(r,F)}var a=c.call(T,L)}else{if(l.substring(0,6)==="WEBVTT")var V=B.concat(Bag(this,l,w));else{T=B;var M=
T.concat;a:{C=z;if(l[0]==="{")try{this.T||(this.T=new Jt(zRP(C)));var x=this.T.yE(l,w);break a}catch(hK){g.kV(hK);x=[];break a}var v=g.ZQ(l);if(!v||!v.firstChild){var n=Error("Invalid caption track data");n.params=l;throw n;}if(v.firstChild.tagName==="timedtext"){if(Number(v.firstChild.getAttribute("format"))===3){r=v;this.T||(this.T=new UX(zRP(C),this.dF));x=this.T.yE(r,w);break a}var Z=Error("Unsupported subtitles format in web player (Format2)");Z.params=l;throw Z;}if(v.firstChild.tagName==="transcript"){var N=
Error("Unsupported subtitles format in web player (Format1)");N.params=l;throw N;}var TP=Error("Invalid caption track data");TP.params=l;throw TP;}V=M.call(T,x)}a=V}B=a}return B}catch(hK){return this.logger.T(187101178,"Captions parsing failed: "+hK.message+". "),this.clear(),[]}};
nw.prototype.clear=function(){this.T&&this.T.dispose();this.T=null};
nw.prototype.reset=function(){this.T&&this.T.reset()};
nw.prototype.gF=function(){g.K.prototype.gF.call(this);this.clear()};var e_={windowColor:"#080808",windowOpacity:0,textAlign:2,qL:7,mX:50,pU:100,isDefault:!0,Tj:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.G(uk,g.I$);g.I=uk.prototype;g.I.gF=function(){if(this.V||this.RK){var B=this.j.Wu();B&&!B.xd()&&B.R4()}else rps(this,!1);g.I$.prototype.gF.call(this)};
g.I.rL=function(){return this.dF.D("html5_honor_caption_availabilities_in_audio_track")&&this.W!=="LIVE"&&this.W!=="SABR_LIVE"};
g.I.dJ=function(){if(this.sE)return this.V||this.RK;var B=this.getAudioTrack();if(this.rL()){if(!B.captionTracks.length)return!1;if(!this.U)return!0}B=x1c(B,g.Zf(this.dF));return B==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:B==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?HC(this):WwF(this)||HC(this)?!0:bJq(this)};
g.I.load=function(){g.I$.prototype.load.call(this);this.N=this.getAudioTrack();if(this.U)this.T&&(this.MG.clear(),this.V?lGp(this,!0):this.player.getPresentingPlayerType()!==3&&this.U.Wq(this.T,"json3",this.O0),this.V||this.RK||Nd(this)||this.player.A0("captionschanged",g.ro(this.T)));else{var B;this.W==="OFFLINE"?B=new $M(this.player,this.videoData,this.getAudioTrack()):this.W==="SABR_LIVE"?B=new fpI(this.videoData.T,this.player):this.W==="LIVE"?B=new wT(this.videoData.T,this.player):this.W==="INNERTUBE"?
B=new g.A5(this.player,this.videoData,this.getAudioTrack()):B=new g.Uk(this.player,this.videoData.XS,this.videoData.videoId,g.$Lz(this.videoData),this.videoData.Fo,this.videoData.eventId);this.U=B;g.m(this,this.U);this.U.nK(this.O0)}};
g.I.unload=function(){this.V&&this.T?lGp(this,!1):(this.cD&&g.TE(this.cD),this.player.I7("captions"),this.zZ=[],this.U&&this.U.Sb(),this.MG.clear(),this.TZ&&this.player.A$(this.TZ),this.Wm());g.I$.prototype.unload.call(this);this.player.TI();this.player.A0("captionschanged",{})};
g.I.create=function(){this.dJ()&&this.load();var B;a:{var z,T,R;if(this.dF.D("web_player_nitrate_promo_tooltip")&&((z=this.videoData.getPlayerResponse())==null?0:(T=z.captions)==null?0:(R=T.playerCaptionsTracklistRenderer)==null?0:R.enableTouchCaptionsNitrate)){var h,W;if(z=(B=this.videoData.getPlayerResponse())==null?void 0:(h=B.captions)==null?void 0:(W=h.playerCaptionsTracklistRenderer)==null?void 0:W.captionTracks)for(B=g.d(z),h=B.next();!h.done;h=B.next())if(h=h.value,h.kind==="asr"&&h.languageCode===
"en"){B=!0;break a}}B=!1}B&&this.j.publish("showpromotooltip",this.J.element)};
g.I.pX=function(){var B=x1c(this.player.getAudioTrack(),g.Zf(this.dF));var z=B==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?OX(this,this.X):B==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&HC(this)?fw(this):WwF(this)||this.X||bJq(this)?OX(this,this.X):HC(this)?fw(this):null;if(this.V||this.RK){var T=g.h5(this.U.U,!0);B=[];for(var R=0;R<T.length;R++){var h=T[R],W=g.ES("TRACK");W.setAttribute("kind","subtitles");W.setAttribute("label",g.Cb(h));W.setAttribute("srclang",g.oQ(h));W.setAttribute("id",h.toString());
this.RK||W.setAttribute("src",this.U.f6(h,"vtt"));h===z&&W.setAttribute("default","1");B.push(W)}z=this.j.Wu();z.ZT(B);B=z.jk();this.aK&&this.XE.Z(B.textTracks,"change",this.J$I)}else!this.T&&z&&ZP(this,z),this.player.A0("onCaptionsTrackListChanged"),this.player.Pd("onApiChange")};
g.I.J$I=function(){for(var B=this.j.Wu().jk().textTracks,z=null,T=0;T<B.length;T++)if(B[T].mode==="showing")a:{z=g.h5(this.U.U,!0);for(var R=0;R<z.length;R++)if(z[R].toString()===B[T].id){z=z[R];break a}z=null}(this.loaded?this.T:null)!==z&&ZP(this,z,!0)};
g.I.Q_J=function(){!this.T&&this.V||this.unload()};
g.I.Mm=function(B,z,T,R){if(B){var h;wy5(this,(h=this.T)!=null?h:void 0);this.dF.D("html5_sends_cfs_after_caption_loaded")&&Xq(this,null,this.T,this.X,Nd(this));this.U.XV()&&(this.zZ=[],this.j.I7("captions"),YM(this.lO),this.MG.reset());B=this.MG.yE(B,z,T,R);this.dF.D("html5_sends_cfs_after_caption_parsed")&&!this.dF.D("html5_sends_cfs_after_caption_loaded")&&B.length>0&&Xq(this,null,this.T,this.X,Nd(this));z=!this.dF.D("html5_keep_caption_data_after_seek")&&(this.W==="LIVE"||this.W==="SABR_LIVE");
this.player.A$(B,void 0,z);!this.X||this.RK||Nd(this)||g.JS(this.dF)||g.vo(this.dF)||g.f0(this.dF)||this.dF.XE==="shortspage"||this.player.isInline()||(g.TE(this.cD),B=gwc({qL:0,mX:5,pU:5,Jb:2,textAlign:0,Sw:0,lang:"en"}),this.IK=[B],z=["Click "," for settings"],this.eI||(T=new g.oU(g.va()),g.m(this,T),this.eI=T.element),T=B.end-B.start,(R=g.Cb(this.T))&&this.IK.push(new GA(B.start,T,0,B.id,R)),this.IK.push(new GA(B.start,T,0,B.id,z[0]),new GA(B.start,T,0,B.id,this.eI,!0),new GA(B.start,T,0,B.id,
z[1],!0)),this.player.A$(this.IK),g.Bi(this.cD));!this.X||this.RK||Nd(this)||(g.Zf(this.dF)?tt(this,!0):j_(this,!0),this.N&&(this.N.W=this.T),this.player.TI());this.X=!1}};
g.I.onCueRangeEnter=function(B){this.zZ.push(B);YM(this.lO)};
g.I.onCueRangeExit=function(B){g.GU(this.zZ,B);this.U instanceof wT&&this.U.L&&this.player.w2([B]);YM(this.lO)};
g.I.getCaptionWindowContainerId=function(){return this.J.element.id};
g.I.Z2E=function(){C3F(this,this.IK);this.IK=null};
g.I.Y5=function(){var B=this;if(!this.U0||!this.V){this.lO.stop();g.vrB(this.Kf);this.zZ.sort(g.bu);var z=this.zZ;if(this.TZ){var T=g.v6(z,function(W){return this.TZ.indexOf(W)===-1},this);
T.length&&(z=T)}z=g.d(z);for(T=z.next();!T.done;T=z.next())iJR(this,T.value);z=g.d(Object.entries(this.WD));var R=z.next();for(T={};!R.done;T={Bf:void 0,OM:void 0},R=z.next()){var h=g.d(R.value);R=h.next().value;h=h.next().value;T.Bf=R;T.OM=h;this.Kf[T.Bf]?(T.OM.element.parentNode||(T.OM instanceof Kw||T.OM instanceof PC||g.Op(this.WD,function(W){return function(b,l){l!==W.Bf&&b.U.params.qL===W.OM.U.params.qL&&b.U.params.mX===W.OM.U.params.mX&&b.U.params.pU===W.OM.U.params.pU&&(b.dispose(),delete B.WD[l]);
return l===W.Bf}}(T),this),this.J.element.appendChild(T.OM.element)),T.OM.Nb(this.Kf[T.Bf])):(T.OM.dispose(),delete this.WD[T.Bf])}}};
g.I.Sfu=function(){RRF(this,{},!0);this.player.A0("captionssettingschanged")};
g.I.rg=function(){var B=e_.Tj;B={background:B.background,backgroundOpacity:B.backgroundOpacity,charEdgeStyle:B.charEdgeStyle,color:B.color,fontFamily:B.fontFamily,fontSizeIncrement:B.fontSizeIncrement,fontStyle:B.bold&&B.italic?3:B.bold?1:B.italic?2:0,textOpacity:B.textOpacity,windowColor:e_.windowColor,windowOpacity:e_.windowOpacity};var z=f0h()||{};z.background!=null&&(B.background=z.background);z.backgroundOverride!=null&&(B.backgroundOverride=z.backgroundOverride);z.backgroundOpacity!=null&&(B.backgroundOpacity=
z.backgroundOpacity);z.backgroundOpacityOverride!=null&&(B.backgroundOpacityOverride=z.backgroundOpacityOverride);z.charEdgeStyle!=null&&(B.charEdgeStyle=z.charEdgeStyle);z.charEdgeStyleOverride!=null&&(B.charEdgeStyleOverride=z.charEdgeStyleOverride);z.color!=null&&(B.color=z.color);z.colorOverride!=null&&(B.colorOverride=z.colorOverride);z.fontFamily!=null&&(B.fontFamily=z.fontFamily);z.fontFamilyOverride!=null&&(B.fontFamilyOverride=z.fontFamilyOverride);z.fontSizeIncrement!=null&&(B.fontSizeIncrement=
z.fontSizeIncrement);z.fontSizeIncrementOverride!=null&&(B.fontSizeIncrementOverride=z.fontSizeIncrementOverride);z.fontStyle!=null&&(B.fontStyle=z.fontStyle);z.fontStyleOverride!=null&&(B.fontStyleOverride=z.fontStyleOverride);z.textOpacity!=null&&(B.textOpacity=z.textOpacity);z.textOpacityOverride!=null&&(B.textOpacityOverride=z.textOpacityOverride);z.windowColor!=null&&(B.windowColor=z.windowColor);z.windowColorOverride!=null&&(B.windowColorOverride=z.windowColorOverride);z.windowOpacity!=null&&
(B.windowOpacity=z.windowOpacity);z.windowOpacityOverride!=null&&(B.windowOpacityOverride=z.windowOpacityOverride);return B};
g.I.Qs=function(B,z){var T={};Object.assign(T,f0h());Object.assign(T,B);RRF(this,T,z);this.player.A0("captionssettingschanged")};
g.I.Wm=function(){!this.V&&this.loaded&&(g.uW(this.WD,function(B,z){B.dispose();delete this.WD[z]},this),this.Y5())};
g.I.vH=function(B,z){switch(B){case "fontSize":if(isNaN(z))break;B=g.yQ(z,-2,4);this.Qs({fontSizeIncrement:B});return B;case "reload":z&&!this.V&&ZP(this,this.T,!0);break;case "stickyLoading":z!==void 0&&this.dF.J&&(g.Zf(this.dF)?tt(this,!!z):j_(this,!!z));break;case "track":return Lw7(this,z);case "tracklist":return this.U?g.s9(g.h5(this.U.U,!(!z||!z.includeAsr)),function(T){return g.ro(T)}):[];
case "translationLanguages":return this.U?this.U.V.map(function(T){return Object.assign({},T)}):[];
case "sampleSubtitles":this.V||z===void 0||rps(this,!!z);break;case "sampleSubtitlesCustomized":this.V||rps(this,!!z,z);break;case "recommendedTranslationLanguages":return g.jP();case "defaultTranslationSourceTrackIndices":return this.U?this.U.J:[]}};
g.I.getOptions=function(){var B="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.dF.J&&B.push("stickyLoading");return B};
g.I.Nk=function(){var B=this.T;if(this.j.zX("captions")){if(this.dF.D("html5_modify_caption_vss_logging")){var z;return(B=(z=this.videoData.gC)!=null?z:null)?{cc:g.ei5(B)}:{}}if(B)return z=B.vssId,B.translationLanguage&&z&&(z="t"+z+"."+g.oQ(B)),{cc:z}}return{}};
g.I.EOE=function(){this.isSubtitlesOn()?(g.Zf(this.dF)?tt(this,!1):j_(this,!1),wy5(this),ZP(this,null,!0)):this.Zh()};
g.I.Zh=function(){var B=Nd(this)||!this.T?OX(this,!0):this.T;B&&this.fp(B.vssId,"m");this.isSubtitlesOn()||ZP(this,Nd(this)||!this.T?OX(this,!0):this.T,!0)};
g.I.isSubtitlesOn=function(){return!!this.loaded&&!!this.T&&!Nd(this)};
g.I.dSf=function(){var B=Nd(this);HC(this,B)?ZP(this,this.getAudioTrack().T,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.rL()&&(this.X=!1,this.T=null,this.U&&(this.U.dispose(),this.U=null)),this.dJ()&&(B?ZP(this,OX(this,!1),!1):this.load()))};
g.I.Qq=function(B){B&&(this.UE={top:B.top,right:B.right,bottom:B.bottom,left:B.left,width:1-B.left-B.right,height:1-B.top-B.bottom},this.J.element.style.top=this.UE.top*100+"%",this.J.element.style.left=this.UE.left*100+"%",this.J.element.style.width=this.UE.width*100+"%",this.J.element.style.height=this.UE.height*100+"%",this.J.element.style.position="absolute",B=cps(this))&&(this.J.element.style.width=B.width+"px",this.J.element.style.height=B.height+"px")};
g.I.onVideoDataChange=function(B,z){B==="newdata"&&(this.videoData=z,this.loaded&&this.unload(),this.X=!1,this.T=null,this.U&&(this.U.dispose(),this.U=null,this.player.A0("captionschanged",{})),this.dJ()&&this.load())};
g.I.getAudioTrack=function(){return this.player.getAudioTrack()};
g.I.sxF=function(){var B=this.j.Wu();B&&!B.xd()&&B.R4();this.j.isFullscreen()?(this.V=this.sE=!0,this.loaded&&this.pX()):(this.sE=this.dF.controlsType==="3",this.V=TaW(this));ZP(this,this.T)};
g.I.IN=function(){var B,z,T,R=(B=this.videoData.getPlayerResponse())==null?void 0:(z=B.captions)==null?void 0:(T=z.playerCaptionsTracklistRenderer)==null?void 0:T.openTranscriptCommand;R&&this.player.uO("innertubeCommand",R)};
g.I.SZ=function(B,z,T){var R=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,h="";B&&(h=B.vssId,h=h.replace(R,""));var W="";B&&B.getId()&&(W=B.getId()||"");B&&B.getXtags()&&(B=B.getXtags(),B=B.replace(R,""),W=W.concat(";"+B));this.j.SZ(z?h:"",z?W:"",T)};
g.I.fp=function(B,z){B=(B||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");B.length>0&&this.j.fp(B,z)};
g.I.g4=function(){this.U&&this.U.g4()};
g.vd.N9(uk,{Y5:"smucd"});g.Fj("captions",uk);})(_yt_player);
