(function(g){var window=this;'use strict';var Xyc=function(B){B.publish("autonavvisibility")},ZJg=function(B,z){B.uO("onAutonavCoundownStarted",z)},eR7=function(B){var z,T,R;
return B==null?void 0:(z=B.playerOverlays)==null?void 0:(T=z.playerOverlayRenderer)==null?void 0:(R=T.autoplay)==null?void 0:R.playerOverlayAutoplayRenderer},h6=function(B,z,T){g.L2(B.element,"ytp-suggestion-set",!!z.videoId);
var R=z.playlistId;T=z.VQ(T?T:"mqdefault.jpg");var h=null,W=null;z instanceof g.VB&&(z.lengthText?(h=z.lengthText||null,W=z.BS||null):z.lengthSeconds&&(h=g.JC(z.lengthSeconds),W=g.JC(z.lengthSeconds,!0)));var b=!!R;R=b&&g.U2(R).type==="RD";var l=z instanceof g.VB?z.isLivePlayback:null,w=z instanceof g.VB?z.isUpcoming:null,q=z.author,c=z.shortViewCount,L=z.publishedTimeText,C=[],r=[];q&&C.push(q);c&&(C.push(c),r.push(c));L&&r.push(L);T={title:z.title,author:q,author_and_views:C.join(" \u2022 "),aria_label:z.ariaLabel||
g.Ix("Watch $TITLE",{TITLE:z.title}),duration:h,timestamp:W,url:z.Go(),is_live:l,is_upcoming:w,is_list:b,is_mix:R,background:T?"background-image: url("+T+")":"",views_and_publish_time:r.join(" \u2022 "),autoplayAlternativeHeader:z.Dd};z instanceof g.MT&&(T.playlist_length=z.playlistLength);B.update(T)},W_=function(B){var z=B.K(),T=z.W;
g.O.call(this,{B:"a",G:"ytp-autonav-suggestion-card",C:{href:"{{url}}",target:T?z.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{B:"div",nf:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],C:{style:"{{background}}"},S:[{B:"div",C:{"aria-label":"{{timestamp}}"},nf:["ytp-autonav-timestamp"],Yd:"{{duration}}"},{B:"div",nf:["ytp-autonav-live-stamp"],Yd:"Live"},{B:"div",
nf:["ytp-autonav-upcoming-stamp"],Yd:"Upcoming"},{B:"div",G:"ytp-autonav-list-overlay",S:[{B:"div",G:"ytp-autonav-mix-text",Yd:"Mix"},{B:"div",G:"ytp-autonav-mix-icon"}]}]},{B:"div",nf:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],Yd:"{{title}}"},{B:"div",nf:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],Yd:"{{author}}"},{B:"div",nf:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],Yd:"{{views_and_publish_time}}"}]});this.j=B;this.suggestion=
null;this.T=T;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},b4=function(B,z){z=z===void 0?!1:z;
g.O.call(this,{B:"div",G:"ytp-autonav-endscreen-countdown-overlay"});var T=this;this.L=z;this.cancelCommand=this.X=void 0;this.Y=0;this.container=new g.O({B:"div",G:"ytp-autonav-endscreen-countdown-container"});g.m(this,this.container);this.container.Vu(this.element);z=B.K();var R=z.W;this.j=B;this.suggestion=null;this.onVideoDataChange("newdata",this.j.getVideoData());this.Z(B,"videodatachange",this.onVideoDataChange);this.T=new g.O({B:"div",G:"ytp-autonav-endscreen-upnext-container",C:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},S:[{B:"div",G:"ytp-autonav-endscreen-upnext-header"},{B:"div",G:"ytp-autonav-endscreen-upnext-alternative-header",Yd:"{{autoplayAlternativeHeader}}"},{B:"a",G:"ytp-autonav-endscreen-link-container",C:{href:"{{url}}",target:R?z.N:""},S:[{B:"div",G:"ytp-autonav-endscreen-upnext-thumbnail",C:{style:"{{background}}"},S:[{B:"div",C:{"aria-label":"{{timestamp}}"},nf:["ytp-autonav-timestamp"],
Yd:"{{duration}}"},{B:"div",nf:["ytp-autonav-live-stamp"],Yd:"Live"},{B:"div",nf:["ytp-autonav-upcoming-stamp"],Yd:"Upcoming"}]},{B:"div",G:"ytp-autonav-endscreen-video-info",S:[{B:"div",G:"ytp-autonav-endscreen-premium-badge"},{B:"div",G:"ytp-autonav-endscreen-upnext-title",Yd:"{{title}}"},{B:"div",G:"ytp-autonav-endscreen-upnext-author",Yd:"{{author}}"},{B:"div",G:"ytp-autonav-view-and-date",Yd:"{{views_and_publish_time}}"},{B:"div",G:"ytp-autonav-author-and-view",Yd:"{{author_and_views}}"}]}]}]});
g.m(this,this.T);this.T.Vu(this.container.element);R||this.Z(this.T.BD("ytp-autonav-endscreen-link-container"),"click",this.AE);this.j.createClientVe(this.container.element,this,115127);this.j.createClientVe(this.T.BD("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.O({B:"div",G:"ytp-autonav-overlay"});g.m(this,this.overlay);this.overlay.Vu(this.container.element);this.U=new g.O({B:"div",G:"ytp-autonav-endscreen-button-container"});g.m(this,this.U);this.U.Vu(this.container.element);
this.cancelButton=new g.O({B:"button",nf:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button",z.D("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],C:{"aria-label":"Cancel autoplay"},Yd:"Cancel"});g.m(this,this.cancelButton);this.cancelButton.Vu(this.U.element);this.cancelButton.listen("click",this.X7,this);this.j.createClientVe(this.cancelButton.element,this,115129);this.playButton=new g.O({B:"a",nf:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button",
z.D("web_modern_buttons")?"ytp-autonav-endscreen-upnext-button-rounded":""],C:{href:"{{url}}",role:"button","aria-label":"Play next video"},Yd:"Play Now"});g.m(this,this.playButton);this.playButton.Vu(this.U.element);this.playButton.listen("click",this.AE,this);this.j.createServerVe(this.playButton.element,this.playButton,!0);(z=this.j.getVideoData())&&stW(this,z);this.W=new g.Si(function(){EAR(T)},500);
g.m(this,this.W);this.NO();this.Z(B,"autonavvisibility",this.NO);this.j.D("web_autonav_color_transition")&&(this.Z(B,"autonavchange",this.Rl),this.Z(B,"onAutonavCoundownStarted",this.i4I))},Yq=function(B){var z=B.j.ZO(!0,B.j.isFullscreen());
g.L2(B.container.element,"ytp-autonav-endscreen-small-mode",B.UN(z));g.L2(B.container.element,"ytp-autonav-endscreen-is-premium",!!B.suggestion&&!!B.suggestion.lRK);g.L2(B.j.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!B.j.lz());g.L2(B.j.getRootNode(),"countdown-running",B.G5());g.L2(B.container.element,"ytp-player-content",B.j.lz());g.Ml(B.overlay.element,{width:z.width+"px"});if(!B.G5()){B.j.lz()?SdF(B,Math.round(BlF(B)/1E3)):SdF(B);z=!!B.suggestion&&!!B.suggestion.Dd;var T=B.j.lz()||
!z;g.L2(B.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!T&&z);g.L2(B.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",T&&!z);B.U.kW(B.j.lz());g.L2(B.element,"ytp-enable-w2w-color-transitions",zCp(B))}},EAR=function(B){var z=BlF(B),T=Math,R=T.min;
var h=B.Y?Date.now()-B.Y:0;T=R.call(T,h,z);SdF(B,Math.ceil((z-T)/1E3));z-T<=500&&B.G5()?B.select(!0):B.G5()&&B.W.start()},BlF=function(B){if(B.j.isFullscreen()){var z;
B=(z=B.j.getVideoData())==null?void 0:z.tC;return B===-1||B===void 0?8E3:B}return B.j.Zd()>=0?B.j.Zd():g.rk(B.j.K().experiments,"autoplay_time")||1E4},stW=function(B,z){z=z.getWatchNextResponse();
var T,R;z=(T=eR7(z))==null?void 0:(R=T.nextButton)==null?void 0:R.buttonRenderer;B.X=z==null?void 0:z.navigationEndpoint;T=z==null?void 0:z.trackingParams;B.playButton&&T&&B.j.setTrackingParams(B.playButton.element,T)},zCp=function(B){var z;
return!((z=B.j.getVideoData())==null||!z.watchToWatchTransitionRenderer)},SdF=function(B,z){z=z===void 0?-1:z;
B=B.T.BD("ytp-autonav-endscreen-upnext-header");g.zJ(B);if(z>=0){z=String(z);var T="Up next in $SECONDS".match(RegExp("\\$SECONDS","gi"))[0],R="Up next in $SECONDS".indexOf(T);if(R>=0){B.appendChild(g.Sh("Up next in $SECONDS".slice(0,R)));var h=g.ES("span");g.Ye(h,"ytp-autonav-endscreen-upnext-header-countdown-number");g.Wt(h,z);B.appendChild(h);B.appendChild(g.Sh("Up next in $SECONDS".slice(R+T.length)));return}}g.Wt(B,"Up next")},l4=function(B,z){g.O.call(this,{B:"div",
nf:["html5-endscreen","ytp-player-content",z||"base-endscreen"]});this.created=!1;this.player=B},wx=function(B){g.O.call(this,{B:"div",
nf:["ytp-upnext","ytp-player-content"],C:{"aria-label":"{{aria_label}}"},S:[{B:"div",G:"ytp-cued-thumbnail-overlay-image",C:{style:"{{background}}"}},{B:"span",G:"ytp-upnext-top",S:[{B:"span",G:"ytp-upnext-header",Yd:"Up Next"},{B:"span",G:"ytp-upnext-title",Yd:"{{title}}"},{B:"span",G:"ytp-upnext-author",Yd:"{{author}}"}]},{B:"a",G:"ytp-upnext-autoplay-icon",C:{role:"button",href:"{{url}}","aria-label":"Play next video"},S:[{B:"svg",C:{height:"100%",version:"1.1",viewBox:"0 0 72 72",width:"100%"},
S:[{B:"circle",G:"ytp-svg-autoplay-circle",C:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{B:"circle",G:"ytp-svg-autoplay-ring",C:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{B:"path",G:"ytp-svg-fill",C:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{B:"span",G:"ytp-upnext-bottom",S:[{B:"span",G:"ytp-upnext-cancel"},{B:"span",G:"ytp-upnext-paused",
Yd:"Autoplay is paused"}]}]});this.api=B;this.cancelButton=null;this.X=this.BD("ytp-svg-autoplay-ring");this.Y=this.notification=this.T=this.suggestion=null;this.W=new g.Si(this.Df,5E3,this);this.U=0;var z=this.BD("ytp-upnext-cancel");this.cancelButton=new g.O({B:"button",nf:["ytp-upnext-cancel-button","ytp-button"],C:{tabindex:"0","aria-label":"Cancel autoplay"},Yd:"Cancel"});g.m(this,this.cancelButton);this.cancelButton.listen("click",this.VR,this);this.cancelButton.Vu(z);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,
this,115129);g.m(this,this.W);this.api.createClientVe(this.element,this,18788);z=this.BD("ytp-upnext-autoplay-icon");this.Z(z,"click",this.Du);this.api.createClientVe(z,this,115130);this.EP();this.Z(B,"autonavvisibility",this.EP);this.Z(B,"mdxnowautoplaying",this.u1F);this.Z(B,"mdxautoplaycanceled",this.eYG);g.L2(this.element,"ytp-upnext-mobile",this.api.K().U)},TlI=function(B,z){if(z)return z;
if(B.api.isFullscreen()){var T;B=(T=B.api.getVideoData())==null?void 0:T.tC;return B===-1||B===void 0?8E3:B}return B.api.Zd()>=0?B.api.Zd():g.rk(B.api.K().experiments,"autoplay_time")||1E4},RCc=function(B,z){z=TlI(B,z);
var T=Math,R=T.min;var h=(0,g.f)()-B.U;T=R.call(T,h,z);z=z===0?1:Math.min(T/z,1);B.X.setAttribute("stroke-dashoffset",""+-211*(z+1));z>=1&&B.G5()&&B.api.getPresentingPlayerType()!==3?B.select(!0):B.G5()&&B.T.start()},qs=function(B){l4.call(this,B,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.O({B:"div",G:"ytp-suggestion-panel",S:[{B:"div",nf:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],Yd:"More videos"}]});this.J=new g.O({B:"div",G:"ytp-suggestions-container"});this.videos=[];this.Y=null;this.X=this.L=!1;this.U=new b4(this.player);g.m(this,this.U);this.U.Vu(this.element);B.getVideoData().fF?this.T=this.U:(this.T=new wx(B),g.Pw(this.player,this.T.element,4),g.m(this,this.T));this.overlay=new g.O({B:"div",
G:"ytp-autonav-overlay-cancelled-state"});g.m(this,this.overlay);this.overlay.Vu(this.element);this.W=new g.kb(this);g.m(this,this.W);g.m(this,this.table);this.table.Vu(this.element);this.table.show();g.m(this,this.J);this.J.Vu(this.table.element);this.hide()},i4=function(B){var z=B.lz();
z!==B.X&&(B.X=z,Xyc(B.player),B.X?(B.U!==B.T&&B.U.hide(),B.table.hide()):(B.U!==B.T&&B.U.show(),B.table.show()))},c_=function(B,z){g.O.call(this,{B:"button",
nf:["ytp-watch-on-youtube-button","ytp-button"],Yd:"{{content}}"});this.j=B;this.buttonType=this.buttonType=z;this.oJ();this.buttonType===2&&g.ww(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.oJ);this.kW(!0)},LK=function(B,z){l4.call(this,B,"embeds-lite-endscreen");
this.j=B;this.T=z;this.j.createClientVe(this.element,this,156943);this.watchButton=new c_(B,2);g.m(this,this.watchButton);this.watchButton.Vu(this.element);this.hide()},CK=function(B){var z=B.K(),T=g.PG||g.VW?{style:"will-change: opacity"}:void 0,R=z.W,h=["ytp-modern-videowall-still"];
z.U&&h.push("ytp-videowall-show-text");g.O.call(this,{B:"a",nf:h,C:{href:"{{url}}",target:R?z.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{B:"div",G:"ytp-modern-videowall-still-image",C:{style:"{{background}}"},S:[{B:"span",G:"ytp-modern-videowall-still-info-duration",Yd:"{{duration}}"}]},{B:"span",G:"ytp-modern-videowall-still-info",C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-modern-videowall-still-info-bg",S:[{B:"span",
G:"ytp-modern-videowall-still-info-content",C:T,S:[{B:"span",G:"ytp-modern-videowall-still-info-title",Yd:"{{title}}"},{B:"span",G:"ytp-modern-videowall-still-info-author",Yd:"{{author_and_views}}"},{B:"span",G:"ytp-modern-videowall-still-info-live",Yd:"Live"}]}]}]},{B:"span",nf:["ytp-modern-videowall-still-listlabel-regular","ytp-modern-videowall-still-listlabel"],C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-modern-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-modern-videowall-still-listlabel-length",
S:[" (",{B:"span",Yd:"{{playlist_length}}"},")"]}]},{B:"span",nf:["ytp-modern-videowall-still-listlabel-mix","ytp-modern-videowall-still-listlabel"],C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-modern-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",G:"ytp-modern-videowall-still-listlabel-length",Yd:" (50+)"}]}]});this.suggestion=null;this.U=R;this.api=B;this.T=new g.kb(this);g.m(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.Z(B,"videodatachange",
this.onVideoDataChange);B.createServerVe(this.element,this);this.onVideoDataChange()},hCW=function(B){l4.call(this,B,"videowall-endscreen");
var z=this;this.j=B;this.stills=[];this.Y=this.videoData=null;this.W=this.L=!1;this.J=null;g.ww(this.element,"modern-videowall-endscreen");this.U=new g.kb(this);g.m(this,this.U);this.X=new g.Si(function(){g.ww(z.element,"ytp-show-tiles")},0);
g.m(this,this.X);this.table=new g.oU({B:"div",G:"ytp-modern-endscreen-content"});g.m(this,this.table);this.table.Vu(this.element);B.getVideoData().fF?this.T=new b4(B,!0):this.T=new wx(B);g.m(this,this.T);g.Pw(this.player,this.T.element,4);B.createClientVe(this.element,this,158789);this.hide()},rx=function(B){return g.xN(B.player)&&B.O1()&&!B.Y},ow=function(B){var z=B.lz();
z!==B.L&&(B.L=z,Xyc(B.player))},Wyq=function(B){l4.call(this,B,"subscribecard-endscreen");
this.T=new g.O({B:"div",G:"ytp-subscribe-card",S:[{B:"img",G:"ytp-author-image",C:{src:"{{profilePicture}}"}},{B:"div",G:"ytp-subscribe-card-right",S:[{B:"div",G:"ytp-author-name",Yd:"{{author}}"},{B:"div",G:"html5-subscribe-button-container"}]}]});g.m(this,this.T);this.T.Vu(this.element);var z=B.getVideoData();this.subscribeButton=new g.Ek("Subscribe",null,"Unsubscribe",null,!0,!1,z.W3,z.subscribed,"trailer-endscreen",null,B,!1);g.m(this,this.subscribeButton);this.subscribeButton.Vu(this.T.BD("html5-subscribe-button-container"));
this.Z(B,"videodatachange",this.rF);this.rF();this.hide()},FG=function(B){var z=B.K(),T=g.PG||g.VW?{style:"will-change: opacity"}:void 0,R=z.W,h=["ytp-videowall-still"];
z.U&&h.push("ytp-videowall-show-text");g.O.call(this,{B:"a",nf:h,C:{href:"{{url}}",target:R?z.N:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},S:[{B:"div",G:"ytp-videowall-still-image",C:{style:"{{background}}"}},{B:"span",G:"ytp-videowall-still-info",C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-videowall-still-info-bg",S:[{B:"span",G:"ytp-videowall-still-info-content",C:T,S:[{B:"span",G:"ytp-videowall-still-info-title",Yd:"{{title}}"},
{B:"span",G:"ytp-videowall-still-info-author",Yd:"{{author_and_views}}"},{B:"span",G:"ytp-videowall-still-info-live",Yd:"Live"},{B:"span",G:"ytp-videowall-still-info-duration",Yd:"{{duration}}"}]}]}]},{B:"span",nf:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-videowall-still-listlabel-icon"},"Playlist",{B:"span",G:"ytp-videowall-still-listlabel-length",S:[" (",{B:"span",Yd:"{{playlist_length}}"},")"]}]},{B:"span",nf:["ytp-videowall-still-listlabel-mix",
"ytp-videowall-still-listlabel"],C:{"aria-hidden":"true"},S:[{B:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{B:"span",G:"ytp-videowall-still-listlabel-length",Yd:" (50+)"}]}]});this.suggestion=null;this.U=R;this.api=B;this.T=new g.kb(this);g.m(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.Z(B,"videodatachange",this.onVideoDataChange);B.createServerVe(this.element,this);this.onVideoDataChange()},Iw=function(B){l4.call(this,B,"videowall-endscreen");
var z=this;this.j=B;this.Y=0;this.stills=[];this.W=this.videoData=null;this.X=this.J=!1;this.N=null;this.U=new g.kb(this);g.m(this,this.U);this.L=new g.Si(function(){g.ww(z.element,"ytp-show-tiles")},0);
g.m(this,this.L);var T=new g.O({B:"button",nf:["ytp-button","ytp-endscreen-previous"],C:{"aria-label":"Previous"},S:[g.Vy()]});g.m(this,T);T.Vu(this.element);T.listen("click",this.c9,this);this.table=new g.oU({B:"div",G:"ytp-endscreen-content"});g.m(this,this.table);this.table.Vu(this.element);T=new g.O({B:"button",nf:["ytp-button","ytp-endscreen-next"],C:{"aria-label":"Next"},S:[g.Qy()]});g.m(this,T);T.Vu(this.element);T.listen("click",this.P9,this);B.getVideoData().fF?this.T=new b4(B,!0):this.T=
new wx(B);g.m(this,this.T);g.Pw(this.player,this.T.element,4);B.createClientVe(this.element,this,158789);this.hide()},Gl=function(B){return g.xN(B.player)&&B.O1()&&!B.W},dx=function(B){var z=B.lz();
z!==B.J&&(B.J=z,Xyc(B.player))},A6=function(B){l4.call(this,B,"watch-again-on-youtube-endscreen");
this.watchButton=new c_(B,1);g.m(this,this.watchButton);this.watchButton.Vu(this.element);g.TXh(B)&&(this.T=new g.sK(B),g.m(this,this.T),this.U=new g.O({B:"div",nf:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],C:{tabIndex:"-1"},S:[this.T]}),g.m(this,this.U),this.T.Vu(this.U.element),this.U.Vu(this.element));B.createClientVe(this.element,this,156914);this.hide()},w6s=function(B){g.I$.call(this,B);
var z=this;this.endScreen=null;this.U=this.T=this.Y=this.W=!1;this.listeners=new g.kb(this);g.m(this,this.listeners);var T=B.K(),R=B.getVideoData();R=R&&R.limitedPlaybackDurationInSeconds!==0;g.cZ(g.kC(T))&&R&&!g.g4(B)?(this.U=!0,this.endScreen=new LK(B,g.CB(B))):B.isEmbedsShortsMode()?this.endScreen=new A6(B):bqc(B)?(this.W=!0,YTc(this),this.T?this.endScreen=new qs(B):T.D("delhi_modern_endscreen")?this.endScreen=new hCW(B):this.endScreen=new Iw(B)):T.yn?this.endScreen=new Wyq(B):this.endScreen=new l4(B);
g.m(this,this.endScreen);g.Pw(B,this.endScreen.element,4);lOh(this);this.listeners.Z(B,"videodatachange",this.onVideoDataChange,this);this.listeners.Z(B,g.YQ("endscreen"),function(h){z.onCueRangeEnter(h)});
this.listeners.Z(B,g.lu("endscreen"),function(h){z.onCueRangeExit(h)})},YTc=function(B){var z=B.player.getVideoData();
if(!z||B.T===z.Bp&&B.Y===z.fF)return!1;B.T=z.Bp;B.Y=z.fF;return!0},bqc=function(B){B=B.K();
return B.t0&&!B.yn&&!B.disableOrganicUi},lOh=function(B){B.player.I7("endscreen");
var z=B.player.getVideoData();z=new g.Wj(Math.max((z.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var T=new g.Wj(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});B.player.A$([z,T])};
g.M2.prototype.Zd=g.bd(14,function(){return this.app.Zd()});
g.ob.prototype.Zd=g.bd(13,function(){return this.getVideoData().Gb});
g.d4.prototype.C0=g.bd(12,function(B){this.m4().C0(B)});
g.cr.prototype.C0=g.bd(11,function(B){this.T!==B&&(this.T=B,this.rF())});
g.J3.prototype.C0=g.bd(10,function(B){this.overflowButton&&this.overflowButton.C0(B)});
g.d4.prototype.eW=g.bd(9,function(B){this.m4().eW(B)});
g.I8.prototype.eW=g.bd(8,function(B){this.U!==B&&(this.U=B,this.rF())});
g.J3.prototype.eW=g.bd(7,function(B){this.shareButton&&this.shareButton.eW(B)});
g.d4.prototype.uN=g.bd(6,function(B){this.m4().uN(B)});
g.Nb.prototype.uN=g.bd(5,function(B){this.v0!==B&&(this.v0=B,this.RR())});
g.d4.prototype.CG=g.bd(4,function(B){this.m4().CG(B)});
g.J3.prototype.CG=g.bd(3,function(B){this.a5!==B&&(this.a5=B,this.iL())});g.G(W_,g.O);W_.prototype.select=function(){this.j.Dw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Gk||void 0)&&this.j.logClick(this.element)};
W_.prototype.onClick=function(B){g.WO(B,this.j,this.T,this.suggestion.sessionData||void 0)&&this.select()};
W_.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};g.G(b4,g.O);g.I=b4.prototype;g.I.uW=function(B){this.suggestion!==B&&(this.suggestion=B,h6(this.T,B),this.playButton.updateValue("url",this.suggestion.Go()),Yq(this))};
g.I.G5=function(){return this.Y>0};
g.I.YF=function(){this.G5()||(this.Y=Date.now(),EAR(this),ZJg(this.j,BlF(this)),g.L2(this.j.getRootNode(),"countdown-running",this.G5()))};
g.I.eM=function(){this.Js();EAR(this);var B=this.T.BD("ytp-autonav-endscreen-upnext-header");B&&g.Wt(B,"Up next")};
g.I.Js=function(){this.G5()&&(this.W.stop(),this.Y=0)};
g.I.select=function(B){this.j.nextVideo(!1,B===void 0?!1:B);this.Js()};
g.I.AE=function(B){g.WO(B,this.j)&&(B.currentTarget===this.playButton.element?this.j.logClick(this.playButton.element):B.currentTarget===this.T.BD("ytp-autonav-endscreen-link-container")&&(B=this.T.BD("ytp-autonav-endscreen-link-container"),this.j.logVisibility(B,!0),this.j.logClick(B)),this.X?(this.j.uO("innertubeCommand",this.X),this.Js()):this.select())};
g.I.X7=function(){this.j.logClick(this.cancelButton.element);g.Qx(this.j,!0);this.cancelCommand&&this.j.uO("innertubeCommand",this.cancelCommand)};
g.I.onVideoDataChange=function(B,z){stW(this,z);B=z.getWatchNextResponse();var T,R;B=(T=eR7(B))==null?void 0:(R=T.cancelButton)==null?void 0:R.buttonRenderer;this.cancelCommand=B==null?void 0:B.command};
g.I.i4I=function(B){if(zCp(this)){var z=this.j.getVideoData().watchToWatchTransitionRenderer,T=z==null?void 0:z.fromColorPaletteDark;z=z==null?void 0:z.toColorPaletteDark;if(T&&z){var R=this.element;R.style.setProperty("--w2w-start-background-color",g.O0(T.surgeColor));R.style.setProperty("--w2w-start-primary-text-color",g.O0(T.primaryTitleColor));R.style.setProperty("--w2w-start-secondary-text-color",g.O0(T.secondaryTitleColor));R.style.setProperty("--w2w-end-background-color",g.O0(z.surgeColor));
R.style.setProperty("--w2w-end-primary-text-color",g.O0(z.primaryTitleColor));R.style.setProperty("--w2w-end-secondary-text-color",g.O0(z.secondaryTitleColor));R.style.setProperty("--w2w-animation-duration",B+"ms")}g.L2(this.element,"ytp-w2w-animate",!0)}};
g.I.Rl=function(B){this.j.D("web_autonav_color_transition")&&B!==2&&g.L2(this.element,"ytp-w2w-animate",!1)};
g.I.NO=function(){var B=this.j.lz();this.L&&this.vD!==B&&this.kW(B);Yq(this);this.j.logVisibility(this.container.element,B);this.j.logVisibility(this.cancelButton.element,B);this.j.logVisibility(this.T.BD("ytp-autonav-endscreen-link-container"),B);this.j.logVisibility(this.playButton.element,B)};
g.I.UN=function(B){return B.width<400||B.height<459};g.G(l4,g.O);g.I=l4.prototype;g.I.create=function(){this.created=!0};
g.I.destroy=function(){this.created=!1};
g.I.O1=function(){return!1};
g.I.lz=function(){return!1};
g.I.Fv=function(){return!1};g.G(wx,g.O);g.I=wx.prototype;g.I.Df=function(){this.notification&&(this.W.stop(),this.V2(this.Y),this.Y=null,this.notification.close(),this.notification=null)};
g.I.uW=function(B){this.suggestion=B;h6(this,B,"hqdefault.jpg")};
g.I.EP=function(){this.kW(this.api.lz());this.api.logVisibility(this.element,this.api.lz());this.api.logVisibility(this.BD("ytp-upnext-autoplay-icon"),this.api.lz());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.lz())};
g.I.wBO=function(){window.focus();this.Df()};
g.I.YF=function(B){var z=this;this.G5()||(g.w6("a11y-announce","Up Next "+this.suggestion.title),this.U=(0,g.f)(),this.T=new g.Si(function(){RCc(z,B)},25),RCc(this,B),ZJg(this.api,TlI(this,B)));
g.iH(this.element,"ytp-upnext-autoplay-paused")};
g.I.hide=function(){g.O.prototype.hide.call(this)};
g.I.G5=function(){return!!this.T};
g.I.eM=function(){this.Js();this.U=(0,g.f)();RCc(this);g.ww(this.element,"ytp-upnext-autoplay-paused")};
g.I.Js=function(){this.G5()&&(this.T.dispose(),this.T=null)};
g.I.select=function(B){B=B===void 0?!1:B;if(this.api.K().D("autonav_notifications")&&B&&window.Notification&&typeof document.hasFocus==="function"){var z=Notification.permission;z==="default"?Notification.requestPermission():z!=="granted"||document.hasFocus()||(this.Df(),this.notification=new Notification("Up Next",{body:this.suggestion.title,icon:this.suggestion.VQ()}),this.Y=this.Z(this.notification,"click",this.wBO),this.W.start())}this.Js();this.api.nextVideo(!1,B)};
g.I.Du=function(B){!g.hm(this.cancelButton.element,B.target)&&g.WO(B,this.api)&&(this.api.lz()&&this.api.logClick(this.BD("ytp-upnext-autoplay-icon")),this.select())};
g.I.VR=function(){this.api.lz()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Qx(this.api,!0)};
g.I.u1F=function(B){this.api.getPresentingPlayerType();this.show();this.YF(B)};
g.I.eYG=function(){this.api.getPresentingPlayerType();this.Js();this.hide()};
g.I.gF=function(){this.Js();this.Df();g.O.prototype.gF.call(this)};g.G(qs,l4);g.I=qs.prototype;g.I.create=function(){l4.prototype.create.call(this);this.W.Z(this.player,"appresize",this.CC);this.W.Z(this.player,"onVideoAreaChange",this.CC);this.W.Z(this.player,"videodatachange",this.onVideoDataChange);this.W.Z(this.player,"autonavchange",this.wU);this.W.Z(this.player,"onAutonavCancelled",this.lE);this.onVideoDataChange()};
g.I.show=function(){l4.prototype.show.call(this);(this.L||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.Qx(this.player,!1);g.xN(this.player)&&this.O1()&&!this.Y?(i4(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.YF():this.videoData.autonavState===3&&this.T.eM()):(g.Qx(this.player,!0),i4(this));this.CC()};
g.I.hide=function(){l4.prototype.hide.call(this);this.T.eM();i4(this)};
g.I.CC=function(){var B=this.player.ZO(!0,this.player.isFullscreen());i4(this);Yq(this.U);g.L2(this.element,"ytp-autonav-cancelled-small-mode",this.UN(B));g.L2(this.element,"ytp-autonav-cancelled-tiny-mode",this.Ul(B));g.L2(this.element,"ytp-autonav-cancelled-mini-mode",B.width<=400||B.height<=360);this.overlay&&g.Ml(this.overlay.element,{width:B.width+"px"});if(!this.X)for(B=0;B<this.videos.length;B++)g.L2(this.videos[B].element,"ytp-suggestion-card-with-margin",B%2===1)};
g.I.onVideoDataChange=function(){var B=this.player.getVideoData();if(this.videoData!==B&&B){this.videoData=B;if((B=this.videoData.suggestions)&&B.length||this.player.D("web_player_autonav_empty_suggestions_fix")){var z=g.SL(this.videoData);z&&(this.T.uW(z),this.T!==this.U&&this.U.uW(z))}if(B&&B.length)for(z=0;z<qTK.length;++z){var T=qTK[z];if(B&&B[T]){this.videos[z]=new W_(this.player);var R=this.videos[z];T=B[T];R.suggestion!==T&&(R.suggestion=T,h6(R,T));g.m(this,this.videos[z]);this.videos[z].Vu(this.J.element)}}this.CC()}};
g.I.wU=function(B){B===1?(this.L=!1,this.Y=this.videoData.clientPlaybackNonce,this.T.Js(),this.vD&&this.CC()):(this.L=!0,this.lz()&&(B===2?this.T.YF():B===3&&this.T.eM()))};
g.I.lE=function(B){B?this.wU(1):(this.Y=null,this.L=!1)};
g.I.O1=function(){return this.videoData.autonavState!==1};
g.I.UN=function(B){return(B.width<910||B.height<459)&&!this.Ul(B)&&!(B.width<=400||B.height<=360)};
g.I.Ul=function(B){return B.width<800&&!(B.width<=400||B.height<=360)};
g.I.lz=function(){return this.vD&&g.xN(this.player)&&this.O1()&&!this.Y};
var qTK=[1,3,2,4];g.G(c_,g.O);g.I=c_.prototype;g.I.oJ=function(){switch(this.buttonType){case 1:var B="Watch again on YouTube";var z=156915;break;case 2:B="Continue watching on YouTube";z=156942;break;default:B="Continue watching on YouTube",z=156942}this.update({content:B});this.j.hasVe(this.element)&&this.j.destroyVe(this.element);this.j.createClientVe(this.element,this,z)};
g.I.onClick=function(B){this.j.D("web_player_log_click_before_generating_ve_conversion_params")&&this.j.logClick(this.element);g.bx(this.getVideoUrl(),this.j,B);this.j.D("web_player_log_click_before_generating_ve_conversion_params")||this.j.logClick(this.element)};
g.I.getVideoUrl=function(){var B=!0;switch(this.buttonType){case 1:B=!0;break;case 2:B=!1}B=this.j.getVideoUrl(B,!1,!1,!0);var z=this.j.K();if(g.yW(z)){var T={};g.yW(z)&&g.w4(this.j,"addEmbedsConversionTrackingParams",[T]);B=g.Qn(B,T)}return B};
g.I.logVisibility=function(){this.j.logVisibility(this.element,this.vD&&this.V)};
g.I.show=function(){g.O.prototype.show.call(this);this.logVisibility()};
g.I.hide=function(){g.O.prototype.hide.call(this);this.logVisibility()};
g.I.Ga=function(B){g.O.prototype.Ga.call(this,B);this.logVisibility()};g.G(LK,l4);LK.prototype.show=function(){this.player.getPlayerState()!==3&&(l4.prototype.show.call(this),this.T.CG(!0),this.T.eW(!0),this.j.K().S6||this.T.C0(!0),this.j.logVisibility(this.element,!0),this.watchButton.Ga(!0))};
LK.prototype.hide=function(){l4.prototype.hide.call(this);this.T.CG(!1);this.T.eW(!1);this.T.C0(!1);this.j.logVisibility(this.element,!1);this.watchButton.Ga(!1)};g.G(CK,g.O);CK.prototype.select=function(){this.api.Dw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Gk||void 0)&&this.api.logClick(this.element)};
CK.prototype.onClick=function(B){if(g.yW(this.api.K())&&this.api.D("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var z=this.suggestion.Go(),T={};g.Jd(this.api,T);z=g.Qn(z,T);g.bx(z,this.api,B)}else g.WO(B,this.api,this.U,this.suggestion.sessionData||void 0)&&this.select()};
CK.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};
CK.prototype.onVideoDataChange=function(){var B=this.api.getVideoData(),z=this.api.K();this.U=B.Jj?!1:z.W};g.G(hCW,l4);g.I=hCW.prototype;g.I.create=function(){l4.prototype.create.call(this);var B=this.player.getVideoData();B&&(this.videoData=B);this.yL();this.U.Z(this.player,"appresize",this.yL);this.U.Z(this.player,"onVideoAreaChange",this.yL);this.U.Z(this.player,"videodatachange",this.onVideoDataChange);this.U.Z(this.player,"autonavchange",this.rk);this.U.Z(this.player,"onAutonavCancelled",this.F7);B=this.videoData.autonavState;B!==this.J&&this.rk(B);this.U.Z(this.element,"transitionend",this.zy)};
g.I.destroy=function(){g.$K(this.U);g.Lq(this.stills);this.stills=[];l4.prototype.destroy.call(this);g.iH(this.element,"ytp-show-tiles");this.X.stop();this.J=this.videoData.autonavState};
g.I.O1=function(){return this.videoData.autonavState!==1};
g.I.show=function(){var B=this.vD;l4.prototype.show.call(this);g.iH(this.element,"ytp-show-tiles");this.player.K().U?g.zE(this.X):this.X.start();(this.W||this.Y&&this.Y!==this.videoData.clientPlaybackNonce)&&g.Qx(this.player,!1);rx(this)?(ow(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.YF():this.videoData.autonavState===3&&this.T.eM()):(g.Qx(this.player,!0),ow(this));B!==this.vD&&this.player.logVisibility(this.element,!0)};
g.I.hide=function(){var B=this.vD;l4.prototype.hide.call(this);this.T.eM();ow(this);B!==this.vD&&this.player.logVisibility(this.element,!1)};
g.I.zy=function(B){B.target===this.element&&this.yL()};
g.I.yL=function(){var B,z,T,R;var h=((B=this.videoData)==null?0:(z=B.suggestions)==null?0:z.length)?(T=this.videoData)==null?void 0:T.suggestions:[(R=this.videoData)==null?void 0:g.SL(R)];if(h.length){z=this.j.ZO(!0,this.j.isFullscreen());B=Math.floor((z.width-64+16)/(g.yQ(z.width*.27,250,450)+16));z=Math.min(3,Math.floor((z.height-64)/((z.width-64-(B-1)*16)/B*.5625+70)));g.ci(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.ww(this.element,"ytp-modern-endscreen-limit-rows-"+z);g.L2(this.element,"ytp-modern-endscreen-single-item",B===1);g.L2(this.element,"ytp-modern-endscreen-row-0",z===0);B=this.table.element;B.ariaLive="polite";this.T.uW(g.SL(this.videoData));this.T instanceof b4&&Yq(this.T);g.L2(this.element,"ytp-endscreen-takeover",rx(this));ow(this);z=0;B.ariaBusy="true";T=h.length;for(R=0;R<T;R++){var W=R%T,b=this.stills[R];b||(b=new CK(this.player),this.stills[R]=b,B.appendChild(b.element));W=h[W];if(b.suggestion!==
W){b.suggestion=W;var l=b.api.K();h6(b,W,"hqdefault.jpg");if(g.yW(l)&&!b.api.D("web_player_log_click_before_generating_ve_conversion_params")){l=W.Go();var w={};g.w4(b.api,"addEmbedsConversionTrackingParams",[w]);l=g.Qn(l,w);b.updateValue("url",l)}(W=(W=W.sessionData)&&W.itct)&&b.api.setTrackingParams(b.element,W)}z++}this.stills.length=z}};
g.I.onVideoDataChange=function(){var B=this.player.getVideoData(1);this.videoData!==B&&(B!=null&&g.SL(B)?(this.videoData=B,this.yL()):this.player.OE("missg",{vid:(B==null?void 0:B.videoId)||"",cpn:(B==null?void 0:B.clientPlaybackNonce)||""}))};
g.I.Fv=function(){return this.T.G5()};
g.I.rk=function(B){B===1?(this.W=!1,this.Y=this.videoData.clientPlaybackNonce,this.T.Js(),this.vD&&this.yL()):(this.W=!0,this.vD&&rx(this)&&(B===2?this.T.YF():B===3&&this.T.eM()))};
g.I.F7=function(B){if(B){for(B=0;B<this.stills.length;B++)this.j.logVisibility(this.stills[B].element,!0);this.rk(1)}else this.Y=null,this.W=!1;this.yL()};
g.I.lz=function(){return this.vD&&rx(this)};g.G(Wyq,l4);Wyq.prototype.rF=function(){var B=this.player.getVideoData();this.T.update({profilePicture:B.profilePicture,author:B.author});this.subscribeButton.channelId=B.W3;var z=this.subscribeButton;B.subscribed?z.T():z.U()};g.G(FG,g.O);FG.prototype.select=function(){this.api.Dw(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.Gk||void 0)&&this.api.logClick(this.element)};
FG.prototype.onClick=function(B){if(g.yW(this.api.K())&&this.api.D("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var z=this.suggestion.Go(),T={};g.Jd(this.api,T);z=g.Qn(z,T);g.bx(z,this.api,B)}else g.WO(B,this.api,this.U,this.suggestion.sessionData||void 0)&&this.select()};
FG.prototype.onKeyPress=function(B){switch(B.keyCode){case 13:case 32:B.defaultPrevented||(this.select(),B.preventDefault())}};
FG.prototype.onVideoDataChange=function(){var B=this.api.getVideoData(),z=this.api.K();this.U=B.Jj?!1:z.W};g.G(Iw,l4);g.I=Iw.prototype;g.I.create=function(){l4.prototype.create.call(this);var B=this.player.getVideoData();B&&(this.videoData=B);this.IR();this.U.Z(this.player,"appresize",this.IR);this.U.Z(this.player,"onVideoAreaChange",this.IR);this.U.Z(this.player,"videodatachange",this.onVideoDataChange);this.U.Z(this.player,"autonavchange",this.Gq);this.U.Z(this.player,"onAutonavCancelled",this.xE);B=this.videoData.autonavState;B!==this.N&&this.Gq(B);this.U.Z(this.element,"transitionend",this.qC)};
g.I.destroy=function(){g.$K(this.U);g.Lq(this.stills);this.stills=[];l4.prototype.destroy.call(this);g.iH(this.element,"ytp-show-tiles");this.L.stop();this.N=this.videoData.autonavState};
g.I.O1=function(){return this.videoData.autonavState!==1};
g.I.show=function(){var B=this.vD;l4.prototype.show.call(this);g.iH(this.element,"ytp-show-tiles");this.player.K().U?g.zE(this.L):this.L.start();(this.X||this.W&&this.W!==this.videoData.clientPlaybackNonce)&&g.Qx(this.player,!1);Gl(this)?(dx(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3?this.T.select(!0):this.T.YF():this.videoData.autonavState===3&&this.T.eM()):(g.Qx(this.player,!0),dx(this));B!==this.vD&&this.player.logVisibility(this.element,!0)};
g.I.hide=function(){var B=this.vD;l4.prototype.hide.call(this);this.T.eM();dx(this);B!==this.vD&&this.player.logVisibility(this.element,!1)};
g.I.qC=function(B){B.target===this.element&&this.IR()};
g.I.IR=function(){var B,z,T,R;var h=((B=this.videoData)==null?0:(z=B.suggestions)==null?0:z.length)?(T=this.videoData)==null?void 0:T.suggestions:[(R=this.videoData)==null?void 0:g.SL(R)];if(h.length){g.ww(this.element,"ytp-endscreen-paginate");var W=this.j.ZO(!0,this.j.isFullscreen());if(B=g.CB(this.j))B=B.F_()?48:32,W.width-=B*2;var b=W.width/W.height;R=96/54;z=B=2;var l=Math.max(W.width/96,2),w=Math.max(W.height/54,2);T=h.length;var q=T*4;for(q-=4;q>0&&(B<l||z<w);){var c=B/2,L=z/2,C=B<=l-2&&q>=
L*4,r=z<=w-2&&q>=c*4;if((c+1)/L*R/b>b/(c/(L+1)*R)&&r)q-=c*4,z+=2;else if(C)q-=L*4,B+=2;else if(r)q-=c*4,z+=2;else break}R=!1;q>=12&&T*4-q<=6&&(z>=4||B>=4)&&(R=!0);q=B*96;l=z*54;b=q/l<b?W.height/l:W.width/q;b=Math.min(b,2);q=Math.floor(Math.min(W.width,q*b));l=Math.floor(Math.min(W.height,l*b));W=this.table.element;W.ariaLive="polite";g.vt(W,q,l);g.Ml(W,{marginLeft:q/-2+"px",marginTop:l/-2+"px"});this.T.uW(g.SL(this.videoData));this.T instanceof b4&&Yq(this.T);g.L2(this.element,"ytp-endscreen-takeover",
Gl(this));dx(this);q+=4;l+=4;b=0;W.ariaBusy="true";for(w=0;w<B;w++)for(c=0;c<z;c++)if(L=b,r=0,R&&w>=B-2&&c>=z-2?r=1:c%2===0&&w%2===0&&(c<2&&w<2?c===0&&w===0&&(r=2):r=2),L=g.gO(L+this.Y,T),r!==0){C=this.stills[b];C||(C=new FG(this.player),this.stills[b]=C,W.appendChild(C.element));var F=Math.floor(l*c/z),A=Math.floor(q*w/B),a=Math.floor(l*(c+r)/z)-F-4,V=Math.floor(q*(w+r)/B)-A-4;g.pF(C.element,A,F);g.vt(C.element,V,a);g.Ml(C.element,"transitionDelay",(c+w)/20+"s");g.L2(C.element,"ytp-videowall-still-mini",
r===1);g.L2(C.element,"ytp-videowall-still-large",r>2);r=Math.max(V,a);g.L2(C.element,"ytp-videowall-still-round-large",r>=256);g.L2(C.element,"ytp-videowall-still-round-medium",r>96&&r<256);g.L2(C.element,"ytp-videowall-still-round-small",r<=96);L=h[L];C.suggestion!==L&&(C.suggestion=L,r=C.api.K(),F=g.lH(C.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",h6(C,L,F),g.yW(r)&&!C.api.D("web_player_log_click_before_generating_ve_conversion_params")&&(r=L.Go(),F={},g.w4(C.api,"addEmbedsConversionTrackingParams",
[F]),r=g.Qn(r,F),C.updateValue("url",r)),(L=(L=L.sessionData)&&L.itct)&&C.api.setTrackingParams(C.element,L));b++}W.ariaBusy="false";g.L2(this.element,"ytp-endscreen-paginate",b<T);for(h=this.stills.length-1;h>=b;h--)B=this.stills[h],g.RK(B.element),g.c6(B);this.stills.length=b}};
g.I.onVideoDataChange=function(){var B=this.player.getVideoData(1);this.videoData!==B&&(B!=null&&g.SL(B)?(this.Y=0,this.videoData=B,this.IR()):this.player.OE("missg",{vid:(B==null?void 0:B.videoId)||"",cpn:(B==null?void 0:B.clientPlaybackNonce)||""}))};
g.I.P9=function(){this.Y+=this.stills.length;this.IR()};
g.I.c9=function(){this.Y-=this.stills.length;this.IR()};
g.I.Fv=function(){return this.T.G5()};
g.I.Gq=function(B){B===1?(this.X=!1,this.W=this.videoData.clientPlaybackNonce,this.T.Js(),this.vD&&this.IR()):(this.X=!0,this.vD&&Gl(this)&&(B===2?this.T.YF():B===3&&this.T.eM()))};
g.I.xE=function(B){if(B){for(B=0;B<this.stills.length;B++)this.j.logVisibility(this.stills[B].element,!0);this.Gq(1)}else this.W=null,this.X=!1;this.IR()};
g.I.lz=function(){return this.vD&&Gl(this)};g.G(A6,l4);A6.prototype.hasSuggestions=function(){var B;return(B=this.T)==null?void 0:B.hasSuggestions()};
A6.prototype.show=function(){if(this.player.getPlayerState()!==3){l4.prototype.show.call(this);var B=this.U;if(B){var z=this.T.hasSuggestions();g.L2(this.element,"ytp-shorts-branded-ui",z);z?B.show():B.hide()}var T;(T=g.CB(this.player))==null||T.uN(!0);this.player.logVisibility(this.element,!0);this.watchButton.Ga(!0)}};
A6.prototype.hide=function(){l4.prototype.hide.call(this);var B;(B=g.CB(this.player))==null||B.uN(!1);this.player.logVisibility(this.element,!1);this.watchButton.Ga(!1)};g.G(w6s,g.I$);g.I=w6s.prototype;g.I.dJ=function(){var B=this.player.getVideoData(),z=B.mutedAutoplay&&(B.limitedPlaybackDurationInSeconds>0||B.endSeconds>0||B.mutedAutoplayDurationMode!==2);if((this.player.isEmbedsShortsMode()||this.U)&&!z)return!0;var T;var R=!!((B==null?0:g.SL(B))||(B==null?0:(T=B.suggestions)==null?0:T.length));R=!bqc(this.player)||R;B=B.AY;T=this.player.HO();return R&&!B&&!T&&!z};
g.I.lz=function(){return this.endScreen.lz()};
g.I.Ky=function(){return this.lz()?this.endScreen.Fv():!1};
g.I.gF=function(){this.player.I7("endscreen");g.I$.prototype.gF.call(this)};
g.I.load=function(){var B=this.player.getVideoData();var z=B.transitionEndpointAtEndOfStream;if(z&&z.videoId){var T=this.player.bK().vu.get("heartbeat"),R=g.SL(B);!R||z.videoId!==R.videoId||B.JE?(this.player.Dw(z.videoId,void 0,void 0,!0,!0,z),T&&T.nB("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),B=!0):B=!1}else B=!1;B||(g.I$.prototype.load.call(this),this.endScreen.show())};
g.I.unload=function(){g.I$.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.I.onCueRangeEnter=function(B){this.dJ()&&(this.endScreen.created||this.endScreen.create(),B.getId()==="load"&&this.load())};
g.I.onCueRangeExit=function(B){B.getId()==="load"&&this.loaded&&this.unload()};
g.I.onVideoDataChange=function(){lOh(this);this.W&&YTc(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.T?this.endScreen=new qs(this.player):this.endScreen=new Iw(this.player),g.m(this,this.endScreen),g.Pw(this.player,this.endScreen.element,4))};g.Fj("endscreen",w6s);})(_yt_player);
